"""Generated cookiecutter curriculum constants.

DO NOT EDIT: run ``python tools/generate.py`` after changing schema/*.yaml.
"""
from __future__ import annotations

AGENT_BRIDGE_CC = [('1',
  'Exploring the Generative AI Universe',
  'Module 1 gives you the *what*. tensor-to-tenant gives you the *why* — the math in Weeks 7–10, the '
  'primitives in Weeks 31–33, and the production LLM/RAG work in Weeks 70–81.',
  (('Embeddings & what a model "is"',
    'Weeks 7–10',
    'Linear algebra and vector geometry that actually produce embeddings — the math under the vocabulary.'),
   ('Model parameters & training intuition',
    'Weeks 31–33',
    'Engineering micro-projects where you build ML primitives from scratch; parameters stop being magic.'),
   ('RAG at a high level',
    'Week 70',
    'The LLM+RAG phase starts here; you build retrieval pipelines rather than hear a definition.'),
   ('AI agents overview',
    'Weeks 79, 81',
    'The agents weeks where the "agent" label gets an actual implementation.'))),
 ('2',
  'AI Agent Prototyping (No-Code Introduction)',
  'The no-code drag-and-drop hides the machine. Week 6 shows you the shape, Week 51 shows you the deployment '
  'reality, and Week 81 shows you the compiled version.',
  (('What an agent does (no-code view)',
    'Week 6',
    'Orientation weeks where you diagnose tooling and the shape of an agent loop before writing code.'),
   ('Deployment strategies for no-code agents',
    'Week 51',
    'Distributed systems: how services actually get deployed and connected.'),
   ('Agent capabilities without programming',
    'Week 81',
    'The agents phase — you now know what those drag-and-drop nodes compile to.'))),
 ('3',
  'Coding Essentials for AI Programming',
  'Coding essentials give you the vocabulary. Weeks 2–4, 47, 52, and 81 show you what the vocabulary '
  'actually compiles to.',
  (('Python data structures, async & error handling',
    'Weeks 2–4',
    'The tooling phase where you implement the primitives those frameworks wrap.'),
   ('SQL & database frameworks', 'Week 47', 'System design: data modeling, schema, and storage engines.'),
   ('Interacting with APIs',
    'Week 52',
    'Distributed patterns: request/response, contracts, and failure handling.'),
   ('Web frameworks & agent tooling',
    'Week 81',
    'The agents phase where those Flask/FastAPI skills become agent tool servers.'))),
 ('4',
  'Introduction to LangChain',
  'LangChain gives you chains. Weeks 37, 79–80, and 98 give you the composition, state, and production '
  'discipline those chains need.',
  (('LCEL & composable chains',
    'Week 37',
    'Engineering primitives: composing small, testable units — the same discipline as pipeline composition.'),
   ('Model I/O & the LLM abstraction',
    'Week 79',
    'The LLM/RAG phase: you build the abstraction and understand its cost.'),
   ('Memory & conversational apps', 'Week 80', 'RAG and memory systems — state management under the hood.'),
   ('Chains in production',
    'Week 98',
    'Production AI platform: multi-tenant accounting and reliability for LLM pipelines.'))),
 ('5',
  'Prompt Engineering Essentials',
  'Prompting is the surface. Weeks 5, 61, 73, and 79 explain why the surface behaves the way it does.',
  (('Prompt patterns & persona',
    'Week 5',
    'Hypothesis choice: how you phrase an experiment changes the result.'),
   ('Chain of Thought',
    'Week 73',
    'LLM training/RAG — why reasoning traces work, from the model’s perspective.'),
   ('Self Consistency', 'Week 61', 'Experimentation and evaluation: sampling, variance, and aggregation.'),
   ('Prompting with external tools', 'Week 79', 'Agents week: tool-calling contracts and the ReAct loop.'))),
 ('6',
  'RAG Systems Essentials',
  'RAG modules show you retrieval. Weeks 31–33 and 75–78 show you the index, the pipeline, and the failure '
  'modes.',
  (('Vector databases',
    'Weeks 31–33',
    'Build embedding/vector primitives from scratch — you stop trusting the index and build one.'),
   ('Chunking & document processing',
    'Week 36',
    'ML micro-projects: tokenization and preprocessing with measurable trade-offs.'),
   ('Retrieval strategies',
    'Weeks 75–78',
    'The RAG weeks: retrieval pipelines, hybrid search, and evaluation at depth.'),
   ('Hallucination mitigation',
    'Weeks 75–78',
    'Grounding, attribution, and evaluation — the why behind CRAG and self-RAG.'))),
 ('7',
  'Building AI Agents from Scratch & Graph-RAG',
  'Building agents from scratch teaches the loop. Weeks 37, 73, 77, 81 and the Forge’s graph theory teach '
  'the structure that makes the loop correct.',
  (('ReAct loop from scratch',
    'Week 37',
    'Engineering primitives: the loop as a concrete, testable program.'),
   ('Reflection pattern', 'Week 73', 'LLM evaluation: self-critique and feedback loops.'),
   ('Graph RAG with Cypher',
    'Week 77',
    'Graph retrieval — and the Algorithmic Forge graph-theory spine underneath.'),
   ('Entity & relationship extraction',
    'Week 81',
    'Agents phase: knowledge structuring for multi-step reasoning.'))),
 ('7.5',
  'Model Context Protocol (MCP)',
  'MCP standardizes the plug. Weeks 47, 76–77, 87, 98, and 102 build the contract, security, and platform '
  'layers the plug lives in.',
  (('MCP Host / Client / Server architecture',
    'Week 47',
    'Distributed systems: contracts, transports, and service boundaries.'),
   ('Secure tool/data access', 'Weeks 76–77', 'RAG/agents: how tools authenticate, scope, and audit.'),
   ('Transport layer standardization',
    'Week 87',
    'Inference/performance: protocol and interface engineering.'),
   ('MCP in production',
    'Weeks 98, 102',
    'Platform: multi-tenant tool access, rate limiting, and observability.'))),
 ('8',
  'Implementing ReAct Agents with LangChain',
  'The ReAct framework wires the loop. Weeks 80–81, 90, 98, and 99 give it sessions, scale, and tenancy.',
  (('Thought-Action-Observation loop',
    'Week 80',
    'The RAG/agents phase: the loop as a system you can measure.'),
   ('Multi-user support & session ID management',
    'Week 81',
    'Session state and isolation for concurrent users.'),
   ('Tool use at scale', 'Week 90', 'Inference/performance: tool-calling throughput and latency.'),
   ('ReAct in production', 'Weeks 98, 99', 'Platform: multi-tenant agents, quotas, accounting.'))),
 ('9',
  'Building Agents with LangGraph',
  'LangGraph makes state explicit. Weeks 51, 81, 97–98, and 100 teach you state machines, routing, and '
  'durable recovery.',
  (('StateGraph & state management', 'Week 51', 'Distributed systems: explicit state and state transitions.'),
   ('Conditional edges & routing',
    'Week 81',
    'Agents phase: routing logic and control flow in agent systems.'),
   ('Persistence with checkpointers', 'Week 97', 'Platform: durable state and failure recovery.'),
   ('Cyclical execution', 'Weeks 98, 100', 'Production agent platforms and capstones.'))),
 ('10',
  'Building Agents with AutoGen',
  'AutoGen wires conversations. Weeks 81, 96, 98–99, and 100 give you the coordination and execution '
  'discipline.',
  (('Multi-agent conversation', 'Week 81', 'Agents phase: how agents coordinate and hand off.'),
   ('GroupChat & GroupChatManager',
    'Week 96',
    'Platform: orchestration, scheduling, and conversation routing.'),
   ('Code execution & UserProxyAgent',
    'Weeks 98, 99',
    'Platform: sandboxed execution and human-in-the-loop.'),
   ('Collaboration at scale', 'Week 100', 'Capstones: coordination protocols for real workloads.'))),
 ('11',
  'Building Agents with CrewAI',
  'CrewAI organizes roles. Weeks 96–99 give you authorization, orchestration, and delegation at platform '
  'scale.',
  (('Role-based crews', 'Week 96', 'Platform: role/authorization models for agent systems.'),
   ('Task decomposition & dependencies', 'Week 97', 'Platform: workflow and DAG orchestration.'),
   ('Sequential & hierarchical processes', 'Week 98', 'Platform: process design and failure domains.'),
   ('Tool delegation & integration', 'Week 99', 'Platform: scoped tool access and accountability.'))),
 ('12',
  'Agentic AI Design Patterns',
  'Patterns are the vocabulary of agentic design. Weeks 57, 62, 73–74, 81, 98–99 show you where each pattern '
  'is load-bearing.',
  (('Reflection Pattern', 'Week 73', 'LLM evaluation: self-critique, feedback, and iterative refinement.'),
   ('Planning Pattern', 'Week 74', 'LLM/RAG: plan-and-execute architectures.'),
   ('Human-in-the-Loop Pattern', 'Week 57', 'System design: human approval flows and reliability.'),
   ('Multi-Agent & Task Delegation',
    'Weeks 81, 98–99',
    'Agents + platform: coordination and task delegation.'))),
 ('13',
  'Advanced LangGraph Agents',
  'Advanced LangGraph is where the framework meets systems. Weeks 52, 73, 88, 99–100 give it planning, '
  'measurement, and durability.',
  (('Prepared statements for performance',
    'Week 52',
    'System design: query planning and prepared execution.'),
   ('Reflection loops for self-correction', 'Week 73', 'LLM evaluation: self-correction under measurement.'),
   ('Stateful agents with checkpointers', 'Week 88', 'Inference/performance: state persistence cost.'),
   ('Multi-agent coordination patterns', 'Weeks 99, 100', 'Platform + capstones.'))),
 ('14',
  'Advanced AutoGen Agents',
  'Advanced AutoGen scales the conversation. Weeks 62, 96–97, 99, 101 give it hierarchy, sandboxing, and '
  'studio-grade iteration.',
  (('Hierarchical agent structures', 'Week 62', 'MLOps: layered orchestration and environments.'),
   ('Code execution, refinement & testing', 'Week 96', 'Platform: sandboxing and test harnesses.'),
   ('Dynamic group chats', 'Week 97', 'Platform: conversation scheduling.'),
   ('AutoGen Studio prototyping', 'Weeks 99, 101', 'Platform/capstones: rapid iteration on real systems.'))),
 ('15',
  'Advanced CrewAI Agents',
  'Advanced CrewAI composes crews. Weeks 73, 97–99, 102 give you the branching, refinement, and tooling '
  'discipline.',
  (('Hierarchical crews with delegation', 'Week 73', 'LLM phase: delegation structures for reasoning work.'),
   ('Conditional task execution', 'Week 97', 'Platform: workflow branching and state.'),
   ('Iterative refinement loops', 'Week 98', 'Platform: feedback-driven execution.'),
   ('Dynamic tool generation', 'Weeks 99, 102', 'Platform/capstones: self-describing tool interfaces.'))),
 ('16',
  'Agentic RAG using LangGraph',
  'Agentic RAG adds the loop. Weeks 38, 73, 76–78 show you routing, reformulation, and evaluation that make '
  'the loop trustworthy.',
  (('Corrective RAG (CRAG)', 'Weeks 76–77', 'The RAG weeks: correctness loops grounded in evaluation.'),
   ('Self-Reflective RAG', 'Week 78', 'RAG: confidence scoring and self-assessment.'),
   ('Self-Route RAG logic', 'Week 38', 'Engineering micro-projects: routing logic as a primitive.'),
   ('Query reformulation', 'Week 73', 'LLM evaluation: rewrite-and-retrieve trade-offs.'))),
 ('17',
  'Stanford DSPy',
  'DSPy compiles prompts. Weeks 22, 38, 61, 76–79, and 81 turn prompting from a craft into an optimization '
  'problem.',
  (('Signatures & Modules', 'Week 22', 'Math foundations: declarative composition and types.'),
   ('Optimizers (BootstrapFewShot, MIPRO, COPRO)',
    'Weeks 38, 61',
    'Experimentation: automated search over prompts as a measurable optimization.'),
   ('Assertions for constraints', 'Weeks 76–78', 'RAG/agents: enforced constraints and evaluation.'),
   ('DSPy pipelines & agents', 'Weeks 79, 81', 'Agents phase: compiled, self-optimizing agent programs.'))),
 ('18',
  'Kùzu Deep Dive',
  'Kùzu is a graph rocket. Weeks 52, 75, 98, 100 plus the Forge’s graph spine and Capstone 2 give you the '
  'storage, indexing, and algorithm theory under the hood.',
  (('Columnar disk store & compression', 'Week 52', 'System design: storage engines and indexing.'),
   ('CSR adjacency indices', 'Week 75', 'Graph retrieval: how graph joins stay fast.'),
   ('Cypher & graph-first RAG', 'Week 98', 'Platform: graph-powered retrieval at scale.'),
   ('Graph algorithms & concurrency',
    'Weeks 100 · Forge · Capstone 2',
    'The Forge graph-theory spine and the tree-forensics capstone.')))]

AGENT_MODULES_CC = [('1',
  'Exploring the Generative AI Universe',
  ('Fundamentals of Generative AI: Models, Parameters, Embeddings',
   'The GenAI Universe: Components, Key Players, Ecosystem Overview',
   'Introduction to Prompt Engineering Techniques',
   'Basics of Retrieval Augmented Generation (RAG) and its applications',
   'Introduction to AI Agents and their applications')),
 ('2',
  'AI Agent Prototyping (No-Code Introduction)',
  ('Understanding AI Agents: Workings and Use Cases',
   'Features of Agent Development with Code-Free Tools',
   'Building Simple to Advanced AI Agents with NoCode platforms',
   'Customizing and Deploying AI Agents using NoCode tools')),
 ('3',
  'Coding Essentials for AI Programming',
  ('Core Python skills for AI: Advanced data structures, async programming, error handling',
   'Data processing from CSV/JSON files using Python (Pandas, Polars)',
   'SQL and Python frameworks for database management',
   'Interacting with APIs in Python',
   'Prompting LLMs programmatically',
   'Building AI applications with web frameworks',
   'Introduction to popular tools and frameworks for building AI Agents')),
 ('4',
  'Introduction to LangChain',
  ('Core LangChain components: LLMs, Model I/O, Parsers, and Chains',
   'Mastering LangChain Expression Language (LCEL)',
   'Creating efficient prompt templates and output parsers',
   'Developing conversational applications',
   'Implementing advanced LCEL chains')),
 ('5',
  'Prompt Engineering Essentials',
  ('Core principles of crafting effective prompts',
   'Exploration of popular prompt engineering patterns',
   'Hands-on experience with industry-specific use cases',
   'The art of conversational prompting',
   'Advanced prompting techniques: Chain of Thought, Self Consistency',
   'Exploring prompts with external tools')),
 ('6',
  'RAG Systems Essentials',
  ('Document loading and processing techniques',
   'Document chunking strategies',
   'The role of vector databases in RAG systems',
   'Tools for connecting to vector databases',
   'Differentiating vector databases from other DB types',
   'Mastering retrieval strategies',
   'Connecting Vector DBs to LLMs',
   'Common problems and mitigation strategies')),
 ('7',
  'Building AI Agents from Scratch & Graph-RAG',
  ('Structure of an AI agent: Prompts, Tools, and LLMs',
   'Building a simple ReAct style AI Agent',
   'Building an AI Agent based on the Reflection pattern',
   'Extended Study: Graph RAG and Hybrid RAG Workshop')),
 ('7.5',
  'Model Context Protocol (MCP)',
  ('Integrate MCP to create interoperable, pluggable AI agents',
   'Develop MCP Servers that expose local data or tools to LLMs',
   'Develop MCP Clients that talk to MCP servers',
   'Build secure bridges between LangGraph/AutoGen agents and external systems',
   'Use MCP Inspector to debug and validate real-time tool access')),
 ('8',
  'Implementing ReAct Agents with LangChain',
  ('The ReAct Framework: Core Principles and Loop Mechanics',
   'Building a Simple ReAct Style Agent with Tool Use',
   'Adding Conversational Memory to the ReAct Agent',
   'Extending for Real-World Scenarios with Multi-User Support')),
 ('9',
  'Building Agents with LangGraph',
  ('Introduction to LangGraph: Beyond Sequential Chains',
   'Key Components of LangGraph',
   'Architecting Components for Real-World AI Agents',
   'Understanding State Management and Cyclical Execution')),
 ('10',
  'Building Agents with AutoGen',
  ('Introduction to AutoGen: Multi-Agent Conversation',
   'Key Components of AutoGen',
   'Architecting Multi-Agent Collaboration',
   'Managing Conversation Flow and Task Completion')),
 ('11',
  'Building Agents with CrewAI',
  ('Introduction to CrewAI: Orchestrating Agent Crews',
   'Key Components of CrewAI',
   'Architecting Role-Based Agent Collaboration',
   'Understanding Task Execution and Crew Dynamics')),
 ('12',
  'Agentic AI Design Patterns',
  ('The Need for Design Patterns in Agentic AI',
   'Deep Dive into Core Agentic AI Design Patterns',
   'Exploration of Other Relevant Patterns and Best Practices',
   'Best Practices in Agentic System Design')),
 ('13',
  'Advanced LangGraph Agents',
  ('Utilizing Built-ins for ReAct Style Agents',
   'Building ReAct Agents from Scratch',
   'Extending Agents for Multi-User Conversations',
   'Building Reflection and Multi-Agent Systems')),
 ('14',
  'Advanced AutoGen Agents',
  ('Exploring Advanced Agentic Designs',
   'Building Industry-Relevant Agentic Systems',
   'Constructing Code Execution, Refinement, and Testing Systems',
   'Prototyping Agents using AutoGen Studio',
   'Extending for Multi-User Conversations')),
 ('15',
  'Advanced CrewAI Agents',
  ('Building Complex Collaborating Agent Crews',
   'Exploring Advanced Agentic Designs',
   'Building Industry-Relevant Agentic Systems',
   'Learning Frameworks for Multi-Agent Systems')),
 ('16',
  'Agentic RAG using LangGraph',
  ('Research on Agentic RAG Systems',
   'Building Corrective RAG Systems',
   'Extending to Self-Reflective RAG Systems',
   'Implementing Self-Route RAG Logic')),
 ('17',
  'Stanford DSPy',
  ('Design and implement DSPy Signatures',
   'Construct DSPy Modules for complex pipelines',
   'Utilize DSPy Optimizers to automatically tune prompts',
   'Implement DSPy Assertions to enforce constraints',
   'Build sophisticated RAG and agentic systems')),
 ('18',
  'Kùzu Deep Dive',
  ('Kùzu Architecture Crash-Course',
   'Hands-On: Spin & Query',
   'Prepared Statements & Cypher Reuse',
   'Kùzu-Wasm (browser + edge)',
   'Interop Pipelines: Arrow & External Scans',
   'Graph Algorithms (Built-in & Extension)',
   'Concurrency & Embedded Server',
   'Integration Pattern: "Graph-First RAG"'))]

AGENT_PAPERS_CC = [('ReAct: Synergizing Reasoning and Acting in Language Models',
  'arXiv 2210.03629',
  'Foundation of ReAct agents',
  'https://arxiv.org/abs/2210.03629'),
 ('Toolformer: Language Models Can Teach Themselves to Use Tools',
  'arXiv 2302.04761',
  'Self-supervised tool-use agents',
  'https://arxiv.org/abs/2302.04761'),
 ('DSPy: Compiling Declarative Language Model Calls',
  'arXiv 2310.03714',
  'Programming LMs, self-improving pipelines',
  'https://arxiv.org/abs/2310.03714'),
 ('LangGraph: Multi-Agent Workflows',
  'LangChain Docs',
  'Graph-based orchestration, cycles, human-in-the-loop',
  'https://python.langchain.com/docs/langgraph'),
 ('Corrective RAG (CRAG)',
  'arXiv 2401.06999',
  'Self-correcting retrieval loops',
  'https://arxiv.org/abs/2401.06999'),
 ('Model Context Protocol (MCP) Specification',
  'Model Context',
  'Standardized tool/data access for LLMs',
  'https://www.modelcontext.org/'),
 ('Generative Agents: Interactive Simulacra of Human Behavior',
  'arXiv 2304.03442',
  'Simulating multi-agent societies',
  'https://arxiv.org/abs/2304.03442'),
 ('Reflexion: Language Agents with Verbal Reinforcement Learning',
  'arXiv 2303.11366',
  'Self-verbalization and strategy updates',
  'https://arxiv.org/abs/2303.11366'),
 ('AutoGen: Enabling Next-Gen Multi-Agent Applications',
  'Microsoft Research',
  'Collaborative protocol design',
  'https://www.microsoft.com/en-us/research/project/autogen/'),
 ('Kùzu: An Embedded Property Graph Database',
  'Kùzu',
  'Architecture and performance of Kùzu',
  'https://kuzudb.com/blog')]

AGENT_PAPER_WEEKS = {73: [7], 77: [4, 9], 79: [1, 2], 80: [6], 81: [0, 3, 5, 8]}

BRIDGE_PITCH_QUOTE = ("Do Modules 1–18 + Manus capstone in 16 weeks. You'll be an agent builder who can ship. Then, when you hit "
 'the ceiling — when your RAG pipeline breaks at 10k QPS, when your AutoGen crew deadlocks, when your DSPy '
 'optimizer converges to garbage — tensor-to-tenant is waiting. Weeks 22, 38, 57, 75, 88, 98, 99, 102. '
 "That's where the ceiling becomes a floor.")

BRIDGE_PITCH_TAG = 'This is the bridge. Not a merge. A ladder.'

BRIDGE_SUMMARY_CC = [('Module 1', 'Weeks 7–10, 31–33, 70, 79, 81'),
 ('Module 2', 'Weeks 6, 51, 81'),
 ('Module 3', 'Weeks 2–4, 47, 52, 81'),
 ('Module 4', 'Weeks 37, 79, 80, 98'),
 ('Module 5', 'Weeks 5, 61, 73, 79'),
 ('Module 6', 'Weeks 31–33, 36, 75–78'),
 ('Module 7', 'Weeks 37, 73, 77, 81 + Algorithmic Forge graph theory'),
 ('Module 7.5', 'Weeks 47, 76–77, 87, 98, 102'),
 ('Module 8', 'Weeks 80, 81, 90, 98, 99'),
 ('Module 9', 'Weeks 51, 81, 97, 98, 100'),
 ('Module 10', 'Weeks 81, 96, 98, 99, 100'),
 ('Module 11', 'Weeks 96, 97, 98, 99'),
 ('Module 12', 'Weeks 57, 62, 73–74, 81, 98, 99'),
 ('Module 13', 'Weeks 52, 73, 88, 99, 100'),
 ('Module 14', 'Weeks 62, 96, 97, 99, 101'),
 ('Module 15', 'Weeks 73, 97, 98, 99, 102'),
 ('Module 16', 'Weeks 38, 73, 76–78'),
 ('Module 17', 'Weeks 22, 38, 61, 76–79, 81'),
 ('Module 18', 'Weeks 52, 75, 98, 100 + Algorithmic Forge, Capstone 2')]

DARBAR_CATEGORIES = ('array',
 'backtracking',
 'bit manipulation',
 'divide and conquer',
 'dynamic programming',
 'graphs',
 'greedy',
 'hash table',
 'heap',
 'linked list',
 'math',
 'queue',
 'range query',
 'recursion',
 'searching and sorting',
 'stack',
 'string',
 'trees',
 'trie')

DARBAR_DIFFICULTIES = '255 Easy, 240 Medium, 53 Hard'

DARBAR_TOTAL = 548

ENGINEERING_PRIMITIVES = [['retrieval', 'Cosine similarity, KNN, Top-K, reranking, chunking fusion'],
 ['rate_limiting', 'Token bucket, sliding window, leaky bucket'],
 ['caching', 'LRU, TTL, semantic, embedding cache'],
 ['chunking', 'Token-aware, recursive, sentence-aware'],
 ['pii', 'PII span merging, regex/NER redaction'],
 ['metrics', 'Recall@K, MRR, NDCG, ECE, Brier'],
 ['batching', 'Thread-safe inference batcher'],
 ['resilience', 'Retry/backoff, circuit breaker'],
 ['sketches', 'Count-Min, Bloom, HyperLogLog'],
 ['routing', 'Consistent hashing, load balancing'],
 ['ids', 'Snowflake IDs, traffic shaping']]

FORGE_BOSSES = {18: ('Boss fight',
      'Numerical matrix boss',
      'Gaussian elimination, matrix exponentiation, or randomized SVD with numerical-stability notes.',
      '2-3 hr'),
 30: ('Boss fight',
      'Foundations mini-contest',
      'Expectation DP, combinatorics, modular arithmetic, and one optimization search problem.',
      '2-3 hr'),
 45: ('Boss fight',
      'Data-structure mini-contest',
      'Fenwick/segment tree, DSU, hashing, and a range-query workload.',
      '2-3 hr'),
 57: ('Boss fight',
      'Graph/flow boss',
      'Euler indexing plus a flow or matching formulation for scheduling/resource allocation.',
      '2-3 hr'),
 69: ('Boss fight',
      'MLOps algorithm boss',
      'Experiment assignment, greedy rollout, or bandit allocation with a correctness and trade-off report.',
      '2-3 hr'),
 81: ('Boss fight',
      'String/agent boss',
      'Aho–Corasick tool/prompt detector or sequence-DP planner.',
      '2-3 hr'),
 93: ('Boss fight',
      'Inference boss',
      'Priority scheduling, interval allocation, and binary search on capacity backed by a benchmark.',
      '2-3 hr'),
 102: ('Boss fight',
       'Platform tree boss',
       'Euler Tour plus DSU-on-Tree subtree analytics, used as preparation for Capstone 2.',
       '2-3 hr'),
 1: ('Boss fight',
     'Capstone 1',
     'Mo’s algorithm over immutable LLM traces — the required algorithmic capstone.',
     '2-3 hr'),
 2: ('Boss fight',
     'Capstone 2',
     'Euler Tour + DSU on Tree over agent execution trees. Extra depth credit, not required for the LLM '
     'Platform badge.',
     '2-3 hr')}

FORGE_LANES = [(1,
  6,
  'Core',
  'Complexity, arrays, prefix sums, two pointers, binary search, bitmasks',
  'Timed implementation drill with complexity note',
  '45-90 min'),
 (7,
  14,
  'Core',
  'Matrix multiplication, Gaussian elimination, matrix exponentiation, recurrences',
  'From-scratch matrix or recurrence solver',
  '45-90 min'),
 (15,
  22,
  'Supporting',
  'Numerical methods, binary search on answer, ternary search, Newton iteration',
  'Root-finding or optimization comparison',
  '45-120 min'),
 (23,
  30,
  'Core',
  'Probability simulation, expectation DP, combinatorics, inclusion-exclusion, number theory basics',
  'Expectation/counting lab; Week 30 mini-contest',
  '45-90 min'),
 (31,
  37,
  'Core',
  'Heaps, hashing, tries, linked structures, intervals, basic pattern matching',
  'Retrieval/cache primitive plus timed data-structure drill',
  '45-90 min'),
 (38,
  45,
  'Core',
  'Fenwick, segment trees, range queries, sketches, DSU, randomized hashing',
  'Range-query or routing primitive; Week 45 mini-contest',
  '45-90 min'),
 (46,
  52,
  'Core',
  'Graph representation, BFS/DFS, SCC, topological sort, shortest paths',
  'Dependency graph or routing implementation',
  '45-90 min'),
 (53,
  57,
  'Core / Supporting',
  'MST, Euler paths, max flow, min-cost flow, matching',
  'Resource-allocation design; Week 57 graph boss fight',
  '45-120 min'),
 (58,
  69,
  'Core',
  'DP, greedy, bitmask DP, probability DP, experiment assignment',
  'Evaluation or assignment tool with algorithmic analysis',
  '45-90 min'),
 (70,
  81,
  'Core / Supporting',
  'KMP, Aho–Corasick, trie retrieval, sequence DP, suffix-array survey',
  'Pattern detector or retrieval index; Week 81 string boss',
  '45-120 min'),
 (82,
  93,
  'Core / Supporting',
  'Priority scheduling, interval allocation, capacity search, randomized load balancing',
  'Scheduler benchmark; Week 93 inference boss',
  '45-120 min'),
 (94,
  102,
  'Supporting / Boss',
  'Euler indexing, subtree aggregation, DSU on Tree, HLD survey',
  'Tenant-tree query lab; Week 102 platform boss',
  '2-3 hr'),
 (103,
  108,
  'Boss fights',
  "Mo's algorithm, capstone integration, tree forensics",
  'Capstone 1 required; Capstone 2 optional at Week 108',
  '2-3 hr')]

INTERVIEW_DRILLS = [['system_design', 'URL shortener, rate limiter, Dropbox, WhatsApp, Uber, payments, ...'],
 ['coding', "Two pointers, sliding window, DP, graphs, Mo's algorithm, ..."],
 ['behavioral', 'Scope, ownership, ambiguity, perseverance, growth, leadership, ...'],
 ['mocks', 'Mock interview scorecards and retro notes']]

MANDALAS_CC = [('1',
  'Build the learner’s operating system',
  'Weeks 1–7',
  'Disciplined learner',
  'They stop being someone “planning to study AI” and become someone with a functioning learning and '
  'engineering system.'),
 ('2',
  'Learn the geometry beneath intelligence',
  'Weeks 7–14',
  'Linear-algebra thinker',
  'Embeddings, attention and matrix models stop looking like mystical equations. The learner can reason '
  'geometrically.'),
 ('3',
  'Numerical computation and differentiation',
  'Weeks 14–21',
  'Numerical programmer',
  'They begin understanding not only whether an algorithm is mathematically correct, but whether it is '
  'numerically sane.'),
 ('4',
  'Probability, autodiff and statistical inference',
  'Weeks 21–28',
  'Statistical reasoner',
  'They can explain why training and evaluation procedures work — not merely import them.'),
 ('5',
  'Experimentation meets retrieval',
  'Weeks 28–35',
  'Retrieval and experimentation builder',
  'They can now build the primitives behind search, experimentation and traffic control.'),
 ('6',
  'Production reliability and measurable AI',
  'Weeks 35–42',
  'Reliability-minded engineer',
  'They stop thinking only about model output and start thinking about trust, failure, observability and '
  'operational behavior.'),
 ('7',
  'Distributed primitives and design reasoning',
  'Weeks 42–48',
  'Distributed-systems implementer',
  'They can move from implementing one process to reasoning about many machines.'),
 ('8',
  'Classic distributed systems',
  'Weeks 49–55',
  'System designer',
  'They stop naming technologies and start defending architecture.'),
 ('9',
  'From system design to ML product science',
  'Weeks 55–62',
  'ML systems practitioner',
  'They learn that a production ML system begins with a decision and a dataset — not with model training.'),
 ('10',
  'Build a mature experimentation platform',
  'Weeks 62–69',
  'Experimentation engineer',
  'They can distinguish “the metric increased” from “we have trustworthy evidence that the product '
  'improved.”'),
 ('11',
  'Train, align and retrieve with LLMs',
  'Weeks 69–76',
  'LLM training and retrieval engineer',
  'They understand the whole upstream and retrieval lifecycle rather than treating the LLM as a remote magic '
  'endpoint.'),
 ('12',
  'RAG, agents and inference foundations',
  'Weeks 76–83',
  'RAG and agent engineer',
  'They can build an agent and explain where its latency, errors, context and cost come from.'),
 ('13',
  'Become an inference systems engineer',
  'Weeks 83–90',
  'Inference performance engineer',
  'They can diagnose inference rather than simply complain that it is slow.'),
 ('14',
  'Advanced serving and reliable routing',
  'Weeks 90–96',
  'Serving and routing engineer',
  'They can optimize not just a model, but a multi-provider inference service.'),
 ('15',
  'Build the enterprise AI platform',
  'Weeks 97–103',
  'Multi-tenant AI platform engineer',
  'This is where “tensor” finally becomes “tenant.”'),
 ('final',
  'Graduation — portfolio, capstone and interview readiness',
  'Weeks 103–108',
  'Portfolio-backed Staff AI Systems candidate',
  'They no longer need to tell someone they “know AI systems.” They can provide the repository, traces, '
  'benchmarks, design documents and failure tests.')]

MANUS_CAPSTONE_CC = ('Project Manus — Agentic UI Automation',
 'Develop a sophisticated AI agent capable of understanding and autonomously operating both web-based GUIs '
 'and CLIs to achieve complex, multi-step user goals.',
 ('LLM-driven decision-making for action selection and planning',
  'Sophisticated message management for internal state',
  'Advanced web browser automation with DOM understanding',
  'Robust terminal emulation with WebSocket interaction',
  'Text editing capabilities for configuration files',
  'Server infrastructure with API endpoints',
  'Comprehensive logging and telemetry'),
 ('Central Orchestration Service',
  'Modular Tool Interface',
  'Browser Interaction Module (Playwright/Selenium)',
  'Terminal Interaction Module',
  'State Management with LangGraph',
  'Prompt Engineering / DSPy Signatures'),
 'Integration of all course concepts including LangChain, LangGraph, AutoGen, CrewAI, DSPy, MCP, and Kùzu.',
 ('Robust DOM interpretation without brittle selectors',
  'State management across different tools',
  'Error recovery in complex workflows',
  'Adaptation to UI changes',
  'Security considerations for UI automation'),
 ('Correctness and completeness of task execution',
  'Robustness and error handling capabilities',
  'Code quality and architectural design',
  'Integration of course concepts',
  'Presentation and documentation quality'),
 ('Multi-user support with session isolation',
  'Integration with Model Context Protocol',
  'Self-optimization using DSPy',
  'Knowledge graph integration with Kùzu',
  'Advanced planning and reflection mechanisms'),
 'LangGraph, DSPy, MCP, Kùzu, Playwright/Selenium')

PHASES = [('00',
  'Orientation, tooling, and diagnostics',
  1,
  6,
  [(1,
    'Orientation and course OS',
    'Course setup, tracker, repo, weekly template',
    'Course dashboard + README'),
   (2, 'Python engineering refresh', 'Typing, testing, async basics', 'CLI project skeleton with tests'),
   (3, 'Numerical Python', 'NumPy, vectorization, broadcasting', 'Vector math utility library'),
   (4, 'Reproducibility', 'Git, notebooks, experiment tracking', 'Reproducible notebook + Makefile'),
   (5,
    'Math diagnostic and induction',
    'Linear algebra, probability, hypothesis choice, and generalization',
    'Diagnostic report + gap map + paper lab'),
   (6, 'Systems diagnostic', 'HTTP, Docker, APIs, Linux basics', 'Containerized hello-service')]),
 ('01',
  'Mathematical foundations I: linear algebra & numerical methods',
  7,
  18,
  [(7, 'Linear algebra I', 'Vector spaces, span, basis, dimension', 'Problem set + concept map'),
   (8, 'Linear algebra II', 'Linear independence, rank, nullity', 'Solver exercises + notes'),
   (9, 'Linear algebra III', 'Inner products, norms, dual norms', 'Norm/distance library'),
   (10, 'Linear algebra IV', 'Orthogonality, projections, Gram-Schmidt', 'Projection demo'),
   (11, 'Linear algebra V', 'Linear transformations, change of basis', 'Coordinate transform lab'),
   (12, 'Linear algebra VI', 'Eigenvalues, eigenvectors, diagonalization', 'PCA-style mini lab'),
   (13, 'Linear algebra VII', 'PSD matrices, quadratic forms, Rayleigh quotient', 'Proof + visualization'),
   (14, 'Linear algebra VIII', 'SVD, pseudoinverse, low-rank approximation', 'Low-rank compression demo'),
   (15,
    'Numerical linear algebra I',
    'Matrix norms, condition numbers, perturbation',
    'Perturbation experiment'),
   (16, 'Numerical linear algebra II', 'LU, QR, Cholesky decomposition', 'Decomposition library'),
   (17,
    'Numerical linear algebra III',
    'Iterative solvers, power iteration, Krylov methods',
    'Solver benchmark'),
   (18, 'Numerical linear algebra IV', 'Randomized SVD, tensor notation', 'Randomized approximation lab')]),
 ('02',
  'Mathematical foundations II: calculus, autodiff, probability, statistics',
  19,
  30,
  [(19, 'Calculus I', 'Partial derivatives, gradients, directional derivatives', 'Gradient visualizer'),
   (20, 'Calculus II', 'Jacobians, Hessians, Taylor approximations', 'Curvature lab'),
   (21, 'Calculus III', 'Chain rule on computational graphs', 'Manual backprop worksheet'),
   (22, 'Automatic differentiation', 'Forward/reverse mode, JVPs, VJPs', 'Tiny autodiff prototype'),
   (23, 'Probability I', 'Probability spaces, conditioning, Bayes theorem', 'Probability problem set'),
   (24, 'Probability II', 'Random variables, distributions, transformations', 'Simulation notebook'),
   (25, 'Probability III', 'Random vectors, covariance, correlation', 'Covariance/correlation lab'),
   (26, 'Probability IV', 'LLN, CLT, delta method', 'Monte Carlo convergence demo'),
   (27, 'Statistics I', 'MLE, MAP, estimator bias/variance', 'Estimator comparison'),
   (28, 'Statistics II', 'Hypothesis testing, p-values, Type I/II errors', 'Test implementation'),
   (29, 'Statistics III', 'Confidence intervals, bootstrap, permutation tests', 'Bootstrap CI package'),
   (30, 'Statistics IV', 'Power, MDE, sample size, multiple testing', 'Experiment-size calculator')]),
 ('03',
  'Engineering micro-projects and applied ML primitives',
  31,
  45,
  [(31, 'Retrieval math', 'Cosine similarity, exact KNN', 'Vector search mini-lab'),
   (32, 'Top-K systems', 'Memory-bounded KNN, streaming Top-K', 'Heap-based Top-K service'),
   (33, 'Ranking pipelines', 'Dynamic Top-K, two-stage retrieval/reranking', 'Reranking prototype'),
   (34, 'Rate limiting I', 'Sliding-window and token bucket rate limiters', 'API limiter module'),
   (35, 'Caching', 'LRU cache and TTL cache', 'Cache simulator with tests'),
   (36, 'Text chunking', 'Token-aware and recursive sentence chunking', 'Chunking library'),
   (37, 'PII handling', 'PII span merging, regex/NER detection', 'Redaction utility'),
   (38, 'Calibration', 'Expected Calibration Error, Brier score', 'Reliability dashboard'),
   (39, 'Ranking metrics', 'NDCG, MRR, Recall@K', 'Retrieval evaluator'),
   (40, 'Batching', 'Thread-safe inference batcher', 'Concurrent batcher'),
   (41, 'Resilience', 'Retry, exponential backoff, jitter, circuit breaker', 'Fault-tolerance kit'),
   (42, 'Sketches', 'Count-Min Sketch, Bloom filter', 'Probabilistic data structures'),
   (43, 'Cardinality/routing', 'HyperLogLog, consistent hashing', 'Distributed routing lab'),
   (44, 'Load balancing', 'Weighted round robin, rendezvous hashing', 'Load balancer module'),
   (45, 'IDs/traffic', 'Snowflake IDs, leaky bucket, sliding-window counter', 'Platform primitives lab')]),
 ('04',
  'System design and distributed systems fundamentals',
  46,
  57,
  [(46, 'System design framework', 'Requirements, constraints, API design', 'Design doc template'),
   (47, 'Data and APIs', 'Data models, observability, contracts', 'API design exercise'),
   (48, 'Rate limiting design', 'Token bucket, sliding windows at scale', 'Rate limiter design writeup'),
   (49, 'Scaling reads/writes', 'Caching, replication, contention', 'Scaling pattern notes'),
   (50, 'Large blobs', 'Storage, CDN, media pipelines', 'Blob storage design'),
   (51, 'Workflow systems', 'Orchestration vs choreography', 'Workflow state design'),
   (52, 'Schema evolution', 'Backward compatibility, contracts', 'Schema migration plan'),
   (53, 'Case studies I', 'URL shortener, Dropbox', 'Two design docs'),
   (54, 'Case studies II', 'Ticketmaster, News Feed', 'Two design docs'),
   (55, 'Case studies III', 'WhatsApp, LeetCode', 'Two design docs'),
   (56, 'Case studies IV', 'Uber, web crawler', 'Two design docs'),
   (57, 'Case studies V', 'Ad click aggregator, payments', 'Trade-off analysis')]),
 ('05',
  'ML lifecycle, experimentation, and MLOps',
  58,
  69,
  [(58, 'ML problem framing', 'Objectives, constraints, iterative development', 'ML project charter'),
   (59, 'Data quality', 'Labeling, weak supervision, augmentation', 'Data quality checklist'),
   (60, 'Leakage/contamination', 'Detection, eval tracking, versioning', 'Leakage audit'),
   (61, 'Offline evaluation', 'Baselines, slices, confidence intervals', 'Eval harness'),
   (62, 'Online evaluation', 'A/B tests, shadow deployment, canary, bandits', 'Rollout plan'),
   (63, 'A/B calculator', 'Lift, z-score, p-value, confidence intervals', 'analyze_ab_test function'),
   (64, 'Bootstrap methods', 'Paired bootstrap for model comparisons', 'bootstrap_ci package'),
   (65, 'SRM detection', 'Sample-ratio mismatch, chi-square diagnostics', 'SRM detector'),
   (66, 'Feature flags', 'Rules, rollouts, sticky assignment', 'Flag engine'),
   (67, 'Experiment assignment', 'Deterministic assignment, namespaces', 'Assignment service'),
   (68, 'Monitoring', 'Drift, observability, four-layer monitoring', 'Monitoring dashboard spec'),
   (69, 'Production failures', 'Distribution shift, postmortems', 'Incident postmortem template')]),
 ('06',
  'LLM training, RAG, agents, and evaluation',
  70,
  81,
  [(70, 'LLM anatomy', 'Transformer, tokenizer, matmul', 'Model anatomy notes'),
   (71, 'LLM data pipelines', 'Cleaning, deduplication, tokenization', 'Dataset card'),
   (72, 'Fine-tuning', 'SFT, LoRA, QLoRA, DoRA', 'Fine-tuning plan'),
   (73, 'Alignment', 'RLHF, DPO, ORPO, GRPO', 'Preference eval plan'),
   (74, 'Distributed training', 'DDP/FSDP, tensor/pipeline parallelism, ZeRO', 'Training architecture map'),
   (75, 'Vector search', 'HNSW, IVF-PQ, product quantization', 'Index benchmark'),
   (76, 'Retrieval patterns', 'Hybrid search, query rewriting, chunking', 'Retrieval lab'),
   (77, 'Retrieval fusion', 'BM25 + dense + reranker, RRF', 'Fusion service'),
   (78, 'Retrieval eval', 'Query slices, macro metrics, regressions', 'Slice evaluation report'),
   (79, 'Prompt systems', 'Prompt template renderer, version registry', 'Prompt management tool'),
   (80, 'Memory/context', 'Conversation memory, context optimizer', 'Memory service'),
   (81,
    'Agent foundations',
    'ReAct, plan-execute, tool calling, guardrails; agent harness (tool-approval gates, session '
    'persistence/resume, context compaction, sub-agent fan-out, sandboxing vs host-shell)',
    'Agent prototype')]),
 ('07',
  'LLM inference and performance engineering',
  82,
  93,
  [(82, 'GPU performance', 'Compute/memory/overhead regimes, FlashAttention', 'Performance primer notes'),
   (83, 'Inference arithmetic', 'Roofline model, arithmetic intensity', 'Model intensity worksheet'),
   (84, 'PagedAttention/vLLM', 'KV paging, block tables', 'vLLM deployment'),
   (85, 'vLLM internals', 'Scheduler, block manager, code paths', 'Internal anatomy notes'),
   (86, 'vLLM metrics', 'Running/waiting requests, latency histograms', 'Metrics schema'),
   (87, 'Observability', 'Prometheus/Grafana for serving', 'Live inference dashboard'),
   (88,
    'Benchmarking',
    'Request-rate sweeps from 1 to 1000+ concurrent, saturation-point identification at each step',
    'Benchmark methodology doc + one published optimization benchmark (vLLM or SGLang config; public gist or '
    'blog post)'),
   (89,
    'SGLang',
    'RadixAttention, prefix reuse',
    'SGLang comparison report + one published vLLM-vs-SGLang benchmark comparing the W84 and W89 pipeline '
    'configs'),
   (90,
    'Scheduling & MoE Execution',
    'Orca, continuous batching, chunked prefill, MoE all-to-all routing, Warp Decode, COMET overlap',
    'MoE overlap schedule design doc + latency-hiding simulator'),
   (91,
    'Quantization',
    'FP8, AWQ, GPTQ, KV cache compression; INT4 (per-channel, per-group, block-wise) and BitNet-style '
    '1.58-bit frontier',
    'Quality/throughput table with INT4 row (QLoRA 4-bit normal-float as the production-ready path; BitNet '
    'as the research frontier)'),
   (92,
    'Long context & attention alternatives',
    'Medusa, EAGLE, StreamingLLM, KV eviction; linear attention (ELU+1), state-space (Mamba), delta-rule '
    '(DeltaNet/Gated DeltaNet), KDA/Kimi Linear; KV cache vs learned recurrence',
    'Latency/memory lab'),
   (93,
    'Disaggregation',
    'DistServe, Splitwise, Mooncake, autoscaling; Kubernetes topology (KServe + KEDA + HPA) and edge '
    'deployment (ONNX, TensorRT-LLM, WebLLM) as alternative topologies',
    'Disaggregated serving plan + depth-mode sub-deliverable: deploy the W84 pipeline to K8s with HPA-driven '
    'autoscaling on a synthetic spike AND port one vLLM config to ONNX/TensorRT-LLM for edge benchmarking '
    '(Modal A10 fallback if no edge hardware)')]),
 ('08',
  'Production AI platform engineering',
  94,
  102,
  [(94, 'Traffic routing', 'Model router, kill switch, sticky rollout', 'Router service'),
   (95, 'Safe observability', 'PII redaction, end-to-end request tracing', 'Trace + safe logs'),
   (96, 'Fan-out/streaming', 'Partial failures, token stream multiplexing', 'Resilient aggregator'),
   (97, 'Quotas/priority', 'Token budgets, gateway prioritization', 'Quota/priority service'),
   (98, 'Workflow execution', 'DAG scheduler, idempotency', 'Workflow engine'),
   (99, 'Fairness/HA', 'Per-tenant limits, leader election', 'Tenant limiter + HA lab'),
   (100, 'Async infrastructure', 'Distributed work queue, config service', 'Queue/config platform'),
   (101, 'Model lifecycle', 'Health monitor, registry/promotion', 'Model ops pipeline'),
   (102,
    'Cost/safety/caching',
    'Semantic/embedding cache, injection detection, cost attribution',
    'Cost/safety platform')]),
 ('09',
  'Capstone, portfolio, and interview readiness',
  103,
  108,
  [(103, 'Capstone planning', 'Requirements, architecture, eval plan', 'Capstone design doc'),
   (104, 'Capstone build I', 'Core API, retrieval/agent flow', 'Working prototype'),
   (105, 'Capstone build II', 'Evaluation, observability, guardrails', 'Monitored prototype'),
   (106, 'Capstone build III', 'Load testing, optimization, cost tuning', 'Performance report'),
   (107, 'Mock interview week', 'System design, coding, behavioral simulations', 'Mock interview scorecard'),
   (108, 'Final review', 'Portfolio, retrospective, job plan', 'Final portfolio + 30-day plan')])]

PHASE_1 = [(1,
  'Orientation and course OS',
  'Course setup, tracker, repo, weekly template',
  'Course dashboard + README'),
 (2, 'Python engineering refresh', 'Typing, testing, async basics', 'CLI project skeleton with tests'),
 (3, 'Numerical Python', 'NumPy, vectorization, broadcasting', 'Vector math utility library'),
 (4, 'Reproducibility', 'Git, notebooks, experiment tracking', 'Reproducible notebook + Makefile'),
 (5,
  'Math diagnostic and induction',
  'Linear algebra, probability, hypothesis choice, and generalization',
  'Diagnostic report + gap map + paper lab'),
 (6, 'Systems diagnostic', 'HTTP, Docker, APIs, Linux basics', 'Containerized hello-service')]

PHASE_10 = [(103, 'Capstone planning', 'Requirements, architecture, eval plan', 'Capstone design doc'),
 (104, 'Capstone build I', 'Core API, retrieval/agent flow', 'Working prototype'),
 (105, 'Capstone build II', 'Evaluation, observability, guardrails', 'Monitored prototype'),
 (106, 'Capstone build III', 'Load testing, optimization, cost tuning', 'Performance report'),
 (107, 'Mock interview week', 'System design, coding, behavioral simulations', 'Mock interview scorecard'),
 (108, 'Final review', 'Portfolio, retrospective, job plan', 'Final portfolio + 30-day plan')]

PHASE_2 = [(7, 'Linear algebra I', 'Vector spaces, span, basis, dimension', 'Problem set + concept map'),
 (8, 'Linear algebra II', 'Linear independence, rank, nullity', 'Solver exercises + notes'),
 (9, 'Linear algebra III', 'Inner products, norms, dual norms', 'Norm/distance library'),
 (10, 'Linear algebra IV', 'Orthogonality, projections, Gram-Schmidt', 'Projection demo'),
 (11, 'Linear algebra V', 'Linear transformations, change of basis', 'Coordinate transform lab'),
 (12, 'Linear algebra VI', 'Eigenvalues, eigenvectors, diagonalization', 'PCA-style mini lab'),
 (13, 'Linear algebra VII', 'PSD matrices, quadratic forms, Rayleigh quotient', 'Proof + visualization'),
 (14, 'Linear algebra VIII', 'SVD, pseudoinverse, low-rank approximation', 'Low-rank compression demo'),
 (15,
  'Numerical linear algebra I',
  'Matrix norms, condition numbers, perturbation',
  'Perturbation experiment'),
 (16, 'Numerical linear algebra II', 'LU, QR, Cholesky decomposition', 'Decomposition library'),
 (17,
  'Numerical linear algebra III',
  'Iterative solvers, power iteration, Krylov methods',
  'Solver benchmark'),
 (18, 'Numerical linear algebra IV', 'Randomized SVD, tensor notation', 'Randomized approximation lab')]

PHASE_3 = [(19, 'Calculus I', 'Partial derivatives, gradients, directional derivatives', 'Gradient visualizer'),
 (20, 'Calculus II', 'Jacobians, Hessians, Taylor approximations', 'Curvature lab'),
 (21, 'Calculus III', 'Chain rule on computational graphs', 'Manual backprop worksheet'),
 (22, 'Automatic differentiation', 'Forward/reverse mode, JVPs, VJPs', 'Tiny autodiff prototype'),
 (23, 'Probability I', 'Probability spaces, conditioning, Bayes theorem', 'Probability problem set'),
 (24, 'Probability II', 'Random variables, distributions, transformations', 'Simulation notebook'),
 (25, 'Probability III', 'Random vectors, covariance, correlation', 'Covariance/correlation lab'),
 (26, 'Probability IV', 'LLN, CLT, delta method', 'Monte Carlo convergence demo'),
 (27, 'Statistics I', 'MLE, MAP, estimator bias/variance', 'Estimator comparison'),
 (28, 'Statistics II', 'Hypothesis testing, p-values, Type I/II errors', 'Test implementation'),
 (29, 'Statistics III', 'Confidence intervals, bootstrap, permutation tests', 'Bootstrap CI package'),
 (30, 'Statistics IV', 'Power, MDE, sample size, multiple testing', 'Experiment-size calculator')]

PHASE_4 = [(31, 'Retrieval math', 'Cosine similarity, exact KNN', 'Vector search mini-lab'),
 (32, 'Top-K systems', 'Memory-bounded KNN, streaming Top-K', 'Heap-based Top-K service'),
 (33, 'Ranking pipelines', 'Dynamic Top-K, two-stage retrieval/reranking', 'Reranking prototype'),
 (34, 'Rate limiting I', 'Sliding-window and token bucket rate limiters', 'API limiter module'),
 (35, 'Caching', 'LRU cache and TTL cache', 'Cache simulator with tests'),
 (36, 'Text chunking', 'Token-aware and recursive sentence chunking', 'Chunking library'),
 (37, 'PII handling', 'PII span merging, regex/NER detection', 'Redaction utility'),
 (38, 'Calibration', 'Expected Calibration Error, Brier score', 'Reliability dashboard'),
 (39, 'Ranking metrics', 'NDCG, MRR, Recall@K', 'Retrieval evaluator'),
 (40, 'Batching', 'Thread-safe inference batcher', 'Concurrent batcher'),
 (41, 'Resilience', 'Retry, exponential backoff, jitter, circuit breaker', 'Fault-tolerance kit'),
 (42, 'Sketches', 'Count-Min Sketch, Bloom filter', 'Probabilistic data structures'),
 (43, 'Cardinality/routing', 'HyperLogLog, consistent hashing', 'Distributed routing lab'),
 (44, 'Load balancing', 'Weighted round robin, rendezvous hashing', 'Load balancer module'),
 (45, 'IDs/traffic', 'Snowflake IDs, leaky bucket, sliding-window counter', 'Platform primitives lab')]

PHASE_5 = [(46, 'System design framework', 'Requirements, constraints, API design', 'Design doc template'),
 (47, 'Data and APIs', 'Data models, observability, contracts', 'API design exercise'),
 (48, 'Rate limiting design', 'Token bucket, sliding windows at scale', 'Rate limiter design writeup'),
 (49, 'Scaling reads/writes', 'Caching, replication, contention', 'Scaling pattern notes'),
 (50, 'Large blobs', 'Storage, CDN, media pipelines', 'Blob storage design'),
 (51, 'Workflow systems', 'Orchestration vs choreography', 'Workflow state design'),
 (52, 'Schema evolution', 'Backward compatibility, contracts', 'Schema migration plan'),
 (53, 'Case studies I', 'URL shortener, Dropbox', 'Two design docs'),
 (54, 'Case studies II', 'Ticketmaster, News Feed', 'Two design docs'),
 (55, 'Case studies III', 'WhatsApp, LeetCode', 'Two design docs'),
 (56, 'Case studies IV', 'Uber, web crawler', 'Two design docs'),
 (57, 'Case studies V', 'Ad click aggregator, payments', 'Trade-off analysis')]

PHASE_6 = [(58, 'ML problem framing', 'Objectives, constraints, iterative development', 'ML project charter'),
 (59, 'Data quality', 'Labeling, weak supervision, augmentation', 'Data quality checklist'),
 (60, 'Leakage/contamination', 'Detection, eval tracking, versioning', 'Leakage audit'),
 (61, 'Offline evaluation', 'Baselines, slices, confidence intervals', 'Eval harness'),
 (62, 'Online evaluation', 'A/B tests, shadow deployment, canary, bandits', 'Rollout plan'),
 (63, 'A/B calculator', 'Lift, z-score, p-value, confidence intervals', 'analyze_ab_test function'),
 (64, 'Bootstrap methods', 'Paired bootstrap for model comparisons', 'bootstrap_ci package'),
 (65, 'SRM detection', 'Sample-ratio mismatch, chi-square diagnostics', 'SRM detector'),
 (66, 'Feature flags', 'Rules, rollouts, sticky assignment', 'Flag engine'),
 (67, 'Experiment assignment', 'Deterministic assignment, namespaces', 'Assignment service'),
 (68, 'Monitoring', 'Drift, observability, four-layer monitoring', 'Monitoring dashboard spec'),
 (69, 'Production failures', 'Distribution shift, postmortems', 'Incident postmortem template')]

PHASE_7 = [(70, 'LLM anatomy', 'Transformer, tokenizer, matmul', 'Model anatomy notes'),
 (71, 'LLM data pipelines', 'Cleaning, deduplication, tokenization', 'Dataset card'),
 (72, 'Fine-tuning', 'SFT, LoRA, QLoRA, DoRA', 'Fine-tuning plan'),
 (73, 'Alignment', 'RLHF, DPO, ORPO, GRPO', 'Preference eval plan'),
 (74, 'Distributed training', 'DDP/FSDP, tensor/pipeline parallelism, ZeRO', 'Training architecture map'),
 (75, 'Vector search', 'HNSW, IVF-PQ, product quantization', 'Index benchmark'),
 (76, 'Retrieval patterns', 'Hybrid search, query rewriting, chunking', 'Retrieval lab'),
 (77, 'Retrieval fusion', 'BM25 + dense + reranker, RRF', 'Fusion service'),
 (78, 'Retrieval eval', 'Query slices, macro metrics, regressions', 'Slice evaluation report'),
 (79, 'Prompt systems', 'Prompt template renderer, version registry', 'Prompt management tool'),
 (80, 'Memory/context', 'Conversation memory, context optimizer', 'Memory service'),
 (81,
  'Agent foundations',
  'ReAct, plan-execute, tool calling, guardrails; agent harness (tool-approval gates, session '
  'persistence/resume, context compaction, sub-agent fan-out, sandboxing vs host-shell)',
  'Agent prototype')]

PHASE_8 = [(82, 'GPU performance', 'Compute/memory/overhead regimes, FlashAttention', 'Performance primer notes'),
 (83, 'Inference arithmetic', 'Roofline model, arithmetic intensity', 'Model intensity worksheet'),
 (84, 'PagedAttention/vLLM', 'KV paging, block tables', 'vLLM deployment'),
 (85, 'vLLM internals', 'Scheduler, block manager, code paths', 'Internal anatomy notes'),
 (86, 'vLLM metrics', 'Running/waiting requests, latency histograms', 'Metrics schema'),
 (87, 'Observability', 'Prometheus/Grafana for serving', 'Live inference dashboard'),
 (88,
  'Benchmarking',
  'Request-rate sweeps from 1 to 1000+ concurrent, saturation-point identification at each step',
  'Benchmark methodology doc + one published optimization benchmark (vLLM or SGLang config; public gist or '
  'blog post)'),
 (89,
  'SGLang',
  'RadixAttention, prefix reuse',
  'SGLang comparison report + one published vLLM-vs-SGLang benchmark comparing the W84 and W89 pipeline '
  'configs'),
 (90,
  'Scheduling & MoE Execution',
  'Orca, continuous batching, chunked prefill, MoE all-to-all routing, Warp Decode, COMET overlap',
  'MoE overlap schedule design doc + latency-hiding simulator'),
 (91,
  'Quantization',
  'FP8, AWQ, GPTQ, KV cache compression; INT4 (per-channel, per-group, block-wise) and BitNet-style 1.58-bit '
  'frontier',
  'Quality/throughput table with INT4 row (QLoRA 4-bit normal-float as the production-ready path; BitNet as '
  'the research frontier)'),
 (92,
  'Long context & attention alternatives',
  'Medusa, EAGLE, StreamingLLM, KV eviction; linear attention (ELU+1), state-space (Mamba), delta-rule '
  '(DeltaNet/Gated DeltaNet), KDA/Kimi Linear; KV cache vs learned recurrence',
  'Latency/memory lab'),
 (93,
  'Disaggregation',
  'DistServe, Splitwise, Mooncake, autoscaling; Kubernetes topology (KServe + KEDA + HPA) and edge '
  'deployment (ONNX, TensorRT-LLM, WebLLM) as alternative topologies',
  'Disaggregated serving plan + depth-mode sub-deliverable: deploy the W84 pipeline to K8s with HPA-driven '
  'autoscaling on a synthetic spike AND port one vLLM config to ONNX/TensorRT-LLM for edge benchmarking '
  '(Modal A10 fallback if no edge hardware)')]

PHASE_9 = [(94, 'Traffic routing', 'Model router, kill switch, sticky rollout', 'Router service'),
 (95, 'Safe observability', 'PII redaction, end-to-end request tracing', 'Trace + safe logs'),
 (96, 'Fan-out/streaming', 'Partial failures, token stream multiplexing', 'Resilient aggregator'),
 (97, 'Quotas/priority', 'Token budgets, gateway prioritization', 'Quota/priority service'),
 (98, 'Workflow execution', 'DAG scheduler, idempotency', 'Workflow engine'),
 (99, 'Fairness/HA', 'Per-tenant limits, leader election', 'Tenant limiter + HA lab'),
 (100, 'Async infrastructure', 'Distributed work queue, config service', 'Queue/config platform'),
 (101, 'Model lifecycle', 'Health monitor, registry/promotion', 'Model ops pipeline'),
 (102,
  'Cost/safety/caching',
  'Semantic/embedding cache, injection detection, cost attribution',
  'Cost/safety platform')]

PREREQUISITES = [('W1–2',
  'Google Like a Pro — Advanced Search Operators',
  'https://www.youtube.com/watch?v=BRiNw490Eq0',
  'Finding the right source, fast',
  'Self-serve research: filter, scope, and verify results instead of hoping Google guesses right.'),
 ('W1–2',
  'How To Read Documentation For Beginners',
  'https://www.youtube.com/watch?v=SWr6NW2osqc',
  'Reading docs as a skill',
  'Navigate any framework docs — quickstarts, references, and changelogs — without a tutorial.'),
 ('W1–2',
  'Git for Beginners',
  'https://www.youtube.com/watch?v=vwj89i2FmG0',
  'Version control fluency',
  'Commit, branch, merge, and recover — the tooling habit every weekly artifact depends on.'),
 ('W1–6',
  'CS50x 2024 Lectures',
  'https://www.youtube.com/playlist?list=PLhQjrBD2T381WAHyx1pq-sBfykqMBI7V4',
  'Computer science fundamentals',
  'C, memory, algorithms, data structures, and web — the shared vocabulary of the whole course.'),
 ('W7–10',
  'Nand to Tetris',
  'https://www.youtube.com/playlist?list=PLrDd_kMiAuNmSb-CKWQqq9oBFN_KNMTaI',
  'A computer from first principles',
  'Build a working computer from NAND gates up — assembler, VM, compiler, OS — and a Tetris game.'),
 ('W11–16',
  'MIT 6.042J — Mathematics for Computer Science',
  'https://www.youtube.com/playlist?list=PLB7540DEDD482705B',
  'Discrete mathematics',
  'Proofs, induction, counting, probability, and graphs — the reasoning the course front-loads in Weeks '
  '7–30.'),
 ('W17–18',
  'YACR — Programming Paradigms Explained',
  'https://codeberg.org/aninokuma/YACR#programming-paradigms-explained-procedural-functional-object-oriented-and-let-it-crash',
  'Programming paradigms',
  'Procedural, functional, object-oriented, and let-it-crash thinking — and why each exists.'),
 ('W19–28',
  'Statistical Learning with Python',
  'https://www.youtube.com/playlist?list=PLoROMvodv4rPP6braWoRt5UCXYZ71GZIQ',
  'Statistics and ML foundations',
  'Supervised and unsupervised learning from the data side — the empirical backbone of every ML week.'),
 ('W29–32',
  'Software Engineering at Google',
  'https://abseil.io/resources/swe-book',
  'Engineering culture and practice',
  'How teams design, test, review, and ship at scale — the professional layer under the technical arc.')]

PREREQ_PLAN = [('W1–2',
  'Learning how to learn',
  'Google Like a Pro · How To Read Documentation · Git for Beginners',
  'Search and docs fluency plus version control — the self-serve skills every later week compounds.'),
 ('W3–6',
  'Computer science foundations',
  'CS50x Lectures 1–6',
  'C, memory, and algorithms — the vocabulary of computation the course assumes at Week 1.'),
 ('W7–10',
  'A computer from first principles',
  'Nand to Tetris',
  'From NAND gates to a CPU, compiler, and OS — nothing is magic anymore.'),
 ('W11–16',
  'Mathematics for computer science',
  'MIT 6.042J',
  'Proofs, induction, counting, probability, and graphs — the exact reasoning Weeks 7–30 rely on.'),
 ('W17–18',
  'Programming paradigms',
  'YACR',
  'Procedural, functional, OO, and let-it-crash — the lenses behind every framework you will read.'),
 ('W19–28',
  'Statistical learning',
  'Statistical Learning with Python',
  'Supervised and unsupervised learning — the empirical core of the ML and evaluation weeks.'),
 ('W29–32',
  'Software engineering at scale',
  'Software Engineering at Google',
  'Design docs, testing, code review, and ownership — the discipline that makes weekly artifacts '
  'professional.'),
 ('W33–36',
  'Synthesis project',
  'All of the above',
  'Consolidate everything into one working project — then Week 1 of the arc starts on solid ground.')]

PROGRAMS = [('foundations', 'Foundations', 1, 30, 'Math, numerical routines, and experimentation toolkit'),
 ('engineering_systems',
  'Engineering + Systems',
  31,
  69,
  'Tested primitives, system designs, MLOps tools, and postmortem'),
 ('llm_platform', 'LLM Platform', 70, 108, 'LLM/RAG work, inference benchmark, platform layer, and capstone')]

RECOVERY_AFTER = [6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86, 94, 102]

RELEASES = [(30, 'Foundations', 'Weeks 1-30', 'Math, numerical routines, and experimentation toolkit', 30),
 (69,
  'Engineering + Systems',
  'Weeks 31-69',
  'Tested primitives, system designs, MLOps tools, and postmortem',
  69),
 (108,
  'LLM Platform',
  'Weeks 70-108',
  'LLM/RAG work, inference benchmark, platform layer, and capstone',
  108)]

SYSTEM_DESIGN_WEEKS = [(46,
  'Delivery framework, requirements, networking, numbers to know',
  'URL shortener / Bitly',
  'Framed design + capacity sheet'),
 (47, 'API design, data modeling, indexing, contracts', 'LeetCode problem service', 'API and schema package'),
 (48,
  'Caching, sharding, consistent hashing, CAP',
  'Rate limiter + distributed cache',
  'Design, key layout, failure table'),
 (49,
  'Replication, read/write scaling, contention',
  'News feed / Instagram',
  'Read path, write path, consistency choice'),
 (50,
  'Large blobs, CDN, metadata, resumable work',
  'Dropbox / Google Docs',
  'Storage design + recovery plan'),
 (51,
  'Queues, workflows, long-running tasks',
  'Job scheduler / Slack job queue',
  'State machine + retry/idempotency plan'),
 (52,
  'Schema evolution, real-time updates, coordination',
  'WhatsApp / notification system',
  'Contract migration + delivery semantics'),
 (53,
  'Search, proximity, crawling, ranking',
  'Yelp / FB post search / web crawler',
  'Index and freshness design'),
 (54,
  'Messaging and social fan-out',
  'FB Live Comments / Tinder / Discord',
  'Fan-out model + hot-key strategy'),
 (55,
  'Scheduling, scarcity, marketplace correctness',
  'Ticketmaster / Uber / local delivery / auction',
  'Reservation invariant + contention test'),
 (56,
  'Streaming, analytics, and data infrastructure',
  'Ad clicks / metrics / Robinhood / Spotify data lake',
  'Stream topology + watermark/replay notes'),
 (57,
  'Integrated architecture and interview boss',
  'ChatGPT / payment system / Figma multiplayer',
  'Staff-level design review + trade-off defense')]

__all__ = ['AGENT_BRIDGE_CC',
 'AGENT_MODULES_CC',
 'AGENT_PAPERS_CC',
 'AGENT_PAPER_WEEKS',
 'BRIDGE_PITCH_QUOTE',
 'BRIDGE_PITCH_TAG',
 'BRIDGE_SUMMARY_CC',
 'DARBAR_CATEGORIES',
 'DARBAR_DIFFICULTIES',
 'DARBAR_TOTAL',
 'ENGINEERING_PRIMITIVES',
 'FORGE_BOSSES',
 'FORGE_LANES',
 'INTERVIEW_DRILLS',
 'MANDALAS_CC',
 'MANUS_CAPSTONE_CC',
 'PHASES',
 'PHASE_1',
 'PHASE_10',
 'PHASE_2',
 'PHASE_3',
 'PHASE_4',
 'PHASE_5',
 'PHASE_6',
 'PHASE_7',
 'PHASE_8',
 'PHASE_9',
 'PREREQUISITES',
 'PREREQ_PLAN',
 'PROGRAMS',
 'RECOVERY_AFTER',
 'RELEASES',
 'SYSTEM_DESIGN_WEEKS']
