"""Generate the website and cookiecutter curriculum views from ``schema/``.

The YAML entity files are the human-maintained source of truth.  The small
``schema/source_data.yaml`` snapshot carries fields that pre-date the schema
migration (for example the bridge prose and the interview side lanes); it is
also generated and is never edited by hand.  This module deliberately keeps
its parser/renderer dependency-free apart from PyYAML so it can run before the
Astro toolchain is installed.

Usage::

    python tools/generate.py          # write generated views
    python tools/generate.py --check  # fail if a write would be required

The renderer preserves the existing TypeScript interfaces, functions, and
comments, replacing only literal ``export const`` values.  This makes a
schema edit produce a small, reviewable diff while guaranteeing deterministic
output on the next run.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import pprint
import re
import sys
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = REPO_ROOT / "schema"
DATA_DIR = REPO_ROOT / "src" / "data"
HOOK_DIR = REPO_ROOT / "cookiecutter" / "hooks"
SOURCE_SNAPSHOT = SCHEMA_DIR / "source_data.yaml"
COOKIECUTTER_SCHEMA = SCHEMA_DIR / "cookiecutter.yaml"
GENERATED_HOOK = HOOK_DIR / "curriculum_generated.py"
HASH_MANIFEST = REPO_ROOT / "tools" / "generated_hashes.json"
TEMPLATE_GENERATED_HOOK = (
    REPO_ROOT / "cookiecutter" / "{{cookiecutter.repo_name}}" / ".curriculum_generated.py"
)

GENERATED_HEADER = "// @generated by tools/generate.py; edit schema/*.yaml instead.\n"


class GenerationError(RuntimeError):
    """Raised when the schema cannot produce a safe generated view."""


# ---------------------------------------------------------------------------
# Minimal JavaScript literal parser
# ---------------------------------------------------------------------------
# The data files intentionally contain only JSON-like literals.  Parsing that
# subset here avoids making Node/TypeScript a prerequisite for the generator.


class _JSParser:
    def __init__(self, text: str):
        self.text = text
        self.i = 0
        self.n = len(text)

    def _skip(self) -> None:
        while self.i < self.n:
            if self.text[self.i].isspace():
                self.i += 1
                continue
            if self.text.startswith("//", self.i):
                end = self.text.find("\n", self.i + 2)
                self.i = self.n if end < 0 else end + 1
                continue
            if self.text.startswith("/*", self.i):
                end = self.text.find("*/", self.i + 2)
                if end < 0:
                    raise GenerationError("unterminated JavaScript comment")
                self.i = end + 2
                continue
            break

    def parse(self) -> Any:
        self._skip()
        value = self._value()
        self._skip()
        if self.i != self.n:
            raise GenerationError(f"unexpected JavaScript text at offset {self.i}")
        return value

    def _value(self) -> Any:
        self._skip()
        if self.i >= self.n:
            raise GenerationError("unexpected end of JavaScript literal")
        char = self.text[self.i]
        if char in "'\"":
            return self._string()
        if char == "[":
            return self._array()
        if char == "{":
            return self._object()

        number = re.match(
            r"-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?",
            self.text[self.i :],
        )
        if number:
            raw = number.group(0)
            self.i += len(raw)
            return float(raw) if any(c in raw for c in ".eE") else int(raw)

        identifier = re.match(r"[A-Za-z_$][\w$]*", self.text[self.i :])
        if identifier:
            raw = identifier.group(0)
            self.i += len(raw)
            return {"true": True, "false": False, "null": None, "undefined": None}.get(raw, raw)
        raise GenerationError(f"unsupported JavaScript literal near {self.text[self.i:self.i + 40]!r}")

    def _string(self) -> str:
        quote = self.text[self.i]
        self.i += 1
        result: list[str] = []
        while self.i < self.n:
            char = self.text[self.i]
            self.i += 1
            if char == quote:
                return "".join(result)
            if char != "\\":
                result.append(char)
                continue
            if self.i >= self.n:
                raise GenerationError("unterminated JavaScript escape")
            escaped = self.text[self.i]
            self.i += 1
            simple = {"n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f", "v": "\v", "0": "\0"}
            if escaped in simple:
                result.append(simple[escaped])
            elif escaped == "u":
                raw = self.text[self.i : self.i + 4]
                if len(raw) != 4 or not re.fullmatch(r"[0-9A-Fa-f]{4}", raw):
                    raise GenerationError("invalid JavaScript unicode escape")
                result.append(chr(int(raw, 16)))
                self.i += 4
            elif escaped == "x":
                raw = self.text[self.i : self.i + 2]
                if len(raw) != 2 or not re.fullmatch(r"[0-9A-Fa-f]{2}", raw):
                    raise GenerationError("invalid JavaScript hex escape")
                result.append(chr(int(raw, 16)))
                self.i += 2
            elif escaped == "\n":
                continue
            else:
                result.append(escaped)
        raise GenerationError("unterminated JavaScript string")

    def _array(self) -> list[Any]:
        self.i += 1  # [
        result: list[Any] = []
        self._skip()
        while self.i < self.n and self.text[self.i] != "]":
            if self.text[self.i] == ",":
                self.i += 1
                self._skip()
                continue
            result.append(self._value())
            self._skip()
            if self.i < self.n and self.text[self.i] == ",":
                self.i += 1
                self._skip()
            elif self.i < self.n and self.text[self.i] != "]":
                raise GenerationError(f"expected comma in array at offset {self.i}")
        if self.i >= self.n:
            raise GenerationError("unterminated JavaScript array")
        self.i += 1
        return result

    def _object(self) -> dict[str, Any]:
        self.i += 1  # {
        result: dict[str, Any] = {}
        self._skip()
        while self.i < self.n and self.text[self.i] != "}":
            if self.text[self.i] in "'\"":
                key = self._string()
            else:
                key_match = re.match(r"[A-Za-z_$][\w$]*", self.text[self.i :])
                if not key_match:
                    raise GenerationError(f"invalid object key at offset {self.i}")
                key = key_match.group(0)
                self.i += len(key)
            self._skip()
            if self.i >= self.n or self.text[self.i] != ":":
                raise GenerationError(f"expected colon after object key at offset {self.i}")
            self.i += 1
            result[key] = self._value()
            self._skip()
            if self.i < self.n and self.text[self.i] == ",":
                self.i += 1
                self._skip()
            elif self.i < self.n and self.text[self.i] != "}":
                raise GenerationError(f"expected comma in object at offset {self.i}")
        if self.i >= self.n:
            raise GenerationError("unterminated JavaScript object")
        self.i += 1
        return result


def _const_expressions(text: str) -> dict[str, tuple[int, int, str]]:
    """Return literal expression slices for exported constants."""
    result: dict[str, tuple[int, int, str]] = {}
    declaration = re.compile(r"export\s+const\s+([A-Za-z_$][\w$]*)\s*(?:.*?)=\s*", re.DOTALL)
    for match in declaration.finditer(text):
        name = match.group(1)
        start = match.end()
        index = start
        depth = 0
        quote: str | None = None
        while index < len(text):
            char = text[index]
            if quote:
                if char == "\\":
                    index += 2
                    continue
                if char == quote:
                    quote = None
            else:
                if char in "'\"`":
                    quote = char
                elif char in "[{(":
                    depth += 1
                elif char in "]})":
                    depth -= 1
                elif char == ";" and depth == 0:
                    break
            index += 1
        expression = text[start:index].strip()
        result[name] = (start, index, expression)
    return result


def _literal_values(text: str) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for name, (_, _, expression) in _const_expressions(text).items():
        if expression.startswith(("[", "{")):
            result[name] = _JSParser(expression).parse()
    return result


# ---------------------------------------------------------------------------
# Schema loading and normalization
# ---------------------------------------------------------------------------


def _load_yaml(path: Path) -> Any:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle) or []


def _records(value: Any) -> list[dict[str, Any]]:
    return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def _number(value: Any) -> int | float | Any:
    if isinstance(value, (int, float)):
        return value
    if isinstance(value, str) and re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def _valid_id(record: dict[str, Any], prefix: str) -> bool:
    return isinstance(record.get("id"), str) and record["id"].startswith(prefix)


def _bootstrap_source_snapshot() -> dict[str, dict[str, Any]]:
    """Bootstrap the snapshot once when a checkout predates it."""
    result: dict[str, dict[str, Any]] = {}
    for path in sorted(DATA_DIR.glob("*.ts")):
        values = _literal_values(path.read_text(encoding="utf-8"))
        if values:
            result[path.stem] = values
    SOURCE_SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SOURCE_SNAPSHOT.write_text(yaml.safe_dump(result, sort_keys=False, allow_unicode=True, width=120), encoding="utf-8")
    return result


def _source_data() -> dict[str, dict[str, Any]]:
    if not SOURCE_SNAPSHOT.exists():
        return _bootstrap_source_snapshot()
    loaded = _load_yaml(SOURCE_SNAPSHOT)
    if not isinstance(loaded, dict):
        raise GenerationError(f"{SOURCE_SNAPSHOT} must contain a mapping")
    return loaded



def _schema_error(path: Path, message: str) -> GenerationError:
    return GenerationError(f"{path.relative_to(REPO_ROOT)}: {message}")


def _validate_ids(records: list[dict[str, Any]], path: Path, *, prefix: str | None = None) -> None:
    seen: set[str] = set()
    for index, record in enumerate(records):
        identifier = record.get("id")
        if not isinstance(identifier, str) or not identifier.strip():
            raise _schema_error(path, f"record {index} has a blank id")
        if prefix and not identifier.startswith(prefix):
            raise _schema_error(path, f"record {index} id {identifier!r} does not start with {prefix!r}")
        if identifier in seen:
            raise _schema_error(path, f"duplicate id {identifier!r} at record {index}")
        seen.add(identifier)


def _agent_module_ref(value: Any) -> str:
    """Return the stable module key used by site and cookiecutter views.

    Bridge-summary records use the display form ``Module 7`` while bridge
    records use the machine-facing form ``7``.  Keeping this conversion in
    one place makes validation and overlaying work for either form (and for
    future modules such as ``7.5``).
    """
    text = str(value).strip()
    if text.lower().startswith("module "):
        return text[7:].strip()
    return text


def _validate_agents_schema(records: list[dict[str, Any]], path: Path) -> None:
    """Validate references shared by the three bridge exports.

    ``source_data.yaml`` is a migration fixture, so checking only duplicate
    record IDs is not enough: a newly-added bridge can otherwise silently
    disappear when its module key does not match the legacy TypeScript view.
    These checks keep the bridge, summary, and pitch rows usable by both
    renderers without imposing a fixed number of modules or rows.
    """
    module_rows = [row for row in records if str(row.get("id", "")).startswith("agent-module-")]
    module_ids: set[str] = set()
    for index, row in enumerate(module_rows):
        module_id = row.get("module_id")
        if module_id in (None, ""):
            raise _schema_error(path, f"agent module record {row.get('id')!r} has no module_id")
        ref = _agent_module_ref(module_id)
        if ref in module_ids:
            raise _schema_error(path, f"duplicate agent module_id {module_id!r}")
        module_ids.add(ref)
        for field in ("title", "topics"):
            if row.get(field) in (None, "") or (field == "topics" and not isinstance(row.get(field), list)):
                raise _schema_error(path, f"agent module record {row.get('id')!r} has invalid {field}")

    bridge_rows = [row for row in records if str(row.get("id", "")).startswith("agent-bridge-")]
    for row in bridge_rows:
        module = row.get("module", row.get("module_id"))
        ref = _agent_module_ref(module) if module not in (None, "") else ""
        if not ref or ref not in module_ids:
            raise _schema_error(path, f"bridge {row.get('id')!r} references unknown module {module!r}")
        rows = row.get("rows")
        if not isinstance(rows, list) or not rows:
            raise _schema_error(path, f"bridge {row.get('id')!r} must contain at least one row")
        for row_index, bridge_row in enumerate(rows):
            if not isinstance(bridge_row, dict):
                raise _schema_error(path, f"bridge {row.get('id')!r} row {row_index} is not a mapping")
            missing = [field for field in ("concept", "weeks", "insight") if bridge_row.get(field) in (None, "")]
            if missing:
                raise _schema_error(path, f"bridge {row.get('id')!r} row {row_index} is missing {', '.join(missing)}")

    summary_rows = [row for row in records if str(row.get("id", "")).startswith("bridge-summary-")]
    for row in summary_rows:
        module = row.get("module")
        ref = _agent_module_ref(module) if module not in (None, "") else ""
        if not ref or ref not in module_ids:
            raise _schema_error(path, f"bridge summary {row.get('id')!r} references unknown module {module!r}")
        if row.get("weeks") in (None, ""):
            raise _schema_error(path, f"bridge summary {row.get('id')!r} has no weeks")


def _validate_curriculum_schema() -> None:
    """Fail before writing anything when the spine schema is inconsistent."""
    weeks_path = SCHEMA_DIR / "weeks.yaml"
    weeks = _records(_load_yaml(weeks_path))
    _validate_ids(weeks, weeks_path)
    phases = [row for row in weeks if _valid_id(row, "phase-")]
    week_rows = [row for row in weeks if _valid_id(row, "week-")]
    recovery = [row for row in weeks if _valid_id(row, "recovery-after-week-")]
    gpu = [row for row in weeks if _valid_id(row, "gpu-week-")]
    if sorted(int(_number(row.get("number"))) for row in phases if row.get("number") is not None) != list(range(1, 11)):
        raise _schema_error(weeks_path, "phases must be numbered 1 through 10 exactly once")
    week_numbers = [int(_number(row.get("week"))) for row in week_rows if row.get("week") is not None]
    if sorted(week_numbers) != list(range(1, 109)):
        raise _schema_error(weeks_path, "weeks must be the contiguous range 1 through 108")
    modes = {"implement", "read_diagram", "deploy_benchmark"}
    invalid_modes = sorted({row.get("mode") for row in week_rows} - modes)
    if invalid_modes:
        raise _schema_error(weeks_path, f"unknown week mode(s): {invalid_modes}")
    phase_ranges: list[tuple[int, int, int]] = []
    for row in phases:
        try:
            number = int(_number(row["number"]))
            start = int(_number(row["start"]))
            end = int(_number(row["end"]))
        except (KeyError, TypeError, ValueError) as error:
            raise _schema_error(weeks_path, f"invalid phase range in {row.get('id')!r}: {error}") from error
        if start > end:
            raise _schema_error(weeks_path, f"phase-{number} has start > end")
        phase_ranges.append((start, end, number))
    phase_ranges.sort()
    expected_start = 1
    for start, end, number in phase_ranges:
        if start != expected_start:
            raise _schema_error(weeks_path, f"phase-{number} leaves a gap/overlap before week {start}")
        expected_start = end + 1
    if expected_start != 109:
        raise _schema_error(weeks_path, "phase ranges must cover weeks 1 through 108")
    valid_phases = {number for _, _, number in phase_ranges}
    for index, row in enumerate(week_rows):
        phase = _number(row.get("phase"))
        if phase not in valid_phases:
            raise _schema_error(weeks_path, f"week record {index} references unknown phase {phase!r}")
    recovery_numbers = [int(_number(row["after_week"])) for row in recovery if row.get("after_week") is not None]
    if len(recovery_numbers) != len(set(recovery_numbers)) or any(number not in week_numbers for number in recovery_numbers):
        raise _schema_error(weeks_path, "recovery windows must reference unique existing weeks")
    expected_gpu = {number for number, row in zip(week_numbers, sorted(week_rows, key=lambda item: int(_number(item["week"])))) if row.get("mode") == "deploy_benchmark"}
    declared_gpu = {int(_number(row["week"])) for row in gpu if row.get("week") is not None}
    if declared_gpu != expected_gpu:
        raise _schema_error(weeks_path, f"gpu-week records {sorted(declared_gpu)} do not match deploy_benchmark weeks {sorted(expected_gpu)}")

    gates_path = SCHEMA_DIR / "gates.yaml"
    gate_rows = _records(_load_yaml(gates_path))
    _validate_ids(gate_rows, gates_path)
    gates = [row for row in gate_rows if row.get("gate") is not None]
    programs = [row for row in gate_rows if row.get("release_week") is not None]
    gate_numbers = sorted(int(_number(row["gate"])) for row in gates)
    if gate_numbers != list(range(1, 11)):
        raise _schema_error(gates_path, "gates must be numbered 1 through 10 exactly once")
    if len(programs) != 3:
        raise _schema_error(gates_path, "programs must contain exactly three releases")
    for row in gates:
        week = _number(row.get("week"))
        if week not in week_numbers:
            raise _schema_error(gates_path, f"gate-{row.get('gate')} references missing week {week!r}")

    # Validate the remaining entity registries too.  The first migration left
    # known empty placeholder rows in a few files; ignore only those explicit
    # legacy placeholders, never a row with meaningful content.
    for entity_name in (
        "agents.yaml",
        "darbar.yaml",
        "engineering.yaml",
        "forge.yaml",
        "interview.yaml",
        "implementation_exercises.yaml",
        "interview_questions.yaml",
        "mandalas.yaml",
        "math.yaml",
        "prerequisites.yaml",
        "resources.yaml",
        "system_design.yaml",
    ):
        entity_path = SCHEMA_DIR / entity_name
        if not entity_path.exists():
            continue
        entity_rows = _records(_load_yaml(entity_path))
        meaningful: list[dict[str, Any]] = []
        for row in entity_rows:
            identifier = row.get("id")
            blank_payload = all(
                value in (None, "", "None", 0, "0", [], {})
                for key, value in row.items()
                if key not in {"id", "tier", "level", "level_note", "seam", "cross_references", "load_bearing_for"}
            )
            if isinstance(identifier, str) and (identifier.endswith("-") or identifier.endswith("-None")) and blank_payload:
                continue
            meaningful.append(row)
        _validate_ids(meaningful, entity_path)
        if entity_name == "agents.yaml":
            _validate_agents_schema(meaningful, entity_path)

    deep_path = SCHEMA_DIR / "deep_dives.yaml"
    if deep_path.exists():
        deep_rows = _records(_load_yaml(deep_path))
        _validate_ids(deep_rows, deep_path)
        tracks = [row for row in deep_rows if row.get("parallel_track") is True]
        for track in tracks:
            artifacts = _records(track.get("primary_artifacts"))
            roles = {artifact.get("role") for artifact in artifacts}
            if roles != {"theory", "production"}:
                raise _schema_error(deep_path, f"{track['id']} must have theory and production artifacts")

def _apply_agent_schema_overrides(
    effective: dict[str, dict[str, Any]], agents_schema: list[dict[str, Any]]
) -> None:
    """Overlay all agent-track exports from ``agents.yaml``.

    The first schema migration used ``source_data.yaml`` as a compatibility
    snapshot and only updated rows that already existed there.  That made a
    new module/bridge appear to be accepted while silently dropping it from
    ``AGENT_BRIDGES`` and ``AGENT_BRIDGE_CC``.  Agent modules, bridge rows,
    summaries, and the pitch are now materialized from their schema records;
    existing snapshot rows are used only to retain legacy fields while a
    record is being migrated.
    """
    agents_target = effective.setdefault("agents", {})

    source_modules = agents_target.get("AGENT_MODULES", [])
    module_by_id = {
        _agent_module_ref(item.get("id")): item
        for item in source_modules
        if isinstance(item, dict) and item.get("id") not in (None, "")
    }
    modules: list[dict[str, Any]] = []
    module_fields = ("title", "theme", "topics", "outcomes", "sections", "labs")
    for row in agents_schema:
        identifier = str(row.get("id", ""))
        if not identifier.startswith("agent-module-"):
            continue
        module_id = row.get("module_id")
        if module_id in (None, ""):
            # Validation reports the actionable error in normal generation;
            # ignoring it here keeps this adapter safe for direct callers.
            continue
        ref = _agent_module_ref(module_id)
        target = copy.deepcopy(module_by_id.get(ref, {}))
        target["id"] = ref
        for field in module_fields:
            if field in row:
                value = row[field]
                if value is None:
                    target.pop(field, None)
                else:
                    target[field] = copy.deepcopy(value)
            elif field in target:
                # Optional fields removed from the canonical row must not
                # survive from the migration snapshot.
                target.pop(field, None)
        modules.append(target)
    if modules:
        agents_target["AGENT_MODULES"] = modules

    source_bridges = agents_target.get("AGENT_BRIDGES", [])
    bridge_by_module = {
        _agent_module_ref(item.get("module")): item
        for item in source_bridges
        if isinstance(item, dict) and item.get("module") not in (None, "")
    }
    bridges: list[dict[str, Any]] = []
    for row in agents_schema:
        identifier = str(row.get("id", ""))
        if not identifier.startswith("agent-bridge-"):
            continue
        module = row.get("module", row.get("module_id"))
        if module in (None, ""):
            continue
        ref = _agent_module_ref(module)
        previous = bridge_by_module.get(ref, {})
        bridge = {
            "module": ref,
            "title": row.get("title", previous.get("title", "")),
            "gap": row.get("gap", previous.get("gap", "")),
            "rows": [],
        }
        bridge_rows = row.get("rows", previous.get("rows", []))
        for bridge_row in bridge_rows or []:
            if not isinstance(bridge_row, dict):
                continue
            bridge["rows"].append(
                {
                    field: copy.deepcopy(bridge_row.get(field, ""))
                    for field in ("concept", "weeks", "insight")
                }
            )
        bridges.append(bridge)
    if bridges:
        agents_target["AGENT_BRIDGES"] = bridges

    summary_rows = [
        row
        for row in agents_schema
        if str(row.get("id", "")).startswith("bridge-summary-")
    ]
    if summary_rows:
        agents_target["BRIDGE_SUMMARY"] = [
            {
                "module": row.get("module", ""),
                "weeks": row.get("weeks", ""),
            }
            for row in summary_rows
        ]

    pitch_rows = [row for row in agents_schema if row.get("id") == "bridge-pitch"]
    if pitch_rows:
        previous_pitch = agents_target.get("BRIDGE_PITCH", {})
        pitch = {
            "quote": pitch_rows[0].get("quote", previous_pitch.get("quote", "")),
            "tag": pitch_rows[0].get("tag", previous_pitch.get("tag", "")),
        }
        agents_target["BRIDGE_PITCH"] = pitch


def _apply_schema_overrides(source: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Overlay canonical entity fields onto the compatibility snapshot.

    The snapshot retains nested prose/side-lane fields that were not in the
    first schema pass.  The spine and release entities are fully controlled by
    their YAML files, so edits to those files always flow into TypeScript and
    the cookiecutter view.
    """
    effective = copy.deepcopy(source)

    # Weeks, phases, and recovery windows.
    weeks_schema = _records(_load_yaml(SCHEMA_DIR / "weeks.yaml"))
    phase_records = [r for r in weeks_schema if _valid_id(r, "phase-") and r.get("number") is not None]
    week_records = [r for r in weeks_schema if _valid_id(r, "week-") and r.get("week") is not None]
    recovery_records = [r for r in weeks_schema if _valid_id(r, "recovery-after-week-") and r.get("after_week") is not None]
    if phase_records:
        effective.setdefault("weeks", {})["PHASES"] = [
            {
                "id": _number(record.get("number")),
                "weeks": record.get("weeks", ""),
                "theme": record.get("theme", ""),
                "start": _number(record.get("start")),
                "end": _number(record.get("end")),
            }
            for record in sorted(phase_records, key=lambda item: _number(item.get("number")))
        ]
    if week_records:
        effective.setdefault("weeks", {})["WEEKS"] = [
            {
                "week": _number(record.get("week")),
                "module": record.get("module", ""),
                "focus": record.get("focus", ""),
                "mode": record.get("mode", ""),
                "deliverable": record.get("deliverable", ""),
            }
            for record in sorted(week_records, key=lambda item: _number(item.get("week")))
        ]
    if recovery_records:
        effective.setdefault("weeks", {})["RECOVERY_AFTER"] = sorted(
            [_number(record["after_week"]) for record in recovery_records]
        )

    # Programs and gates share gates.yaml in the current entity layout.
    gates_schema = _records(_load_yaml(SCHEMA_DIR / "gates.yaml"))
    programs = [record for record in gates_schema if record.get("release_week") is not None]
    gates = [record for record in gates_schema if record.get("gate") is not None]
    if programs:
        effective.setdefault("gates", {})["PROGRAMS"] = [
            {
                "name": record.get("name", ""),
                "weeks": record.get("weeks", ""),
                "releaseWeek": _number(record.get("release_week")),
                "release": record.get("release", ""),
            }
            for record in sorted(programs, key=lambda item: _number(item.get("release_week")))
        ]
    if gates:
        effective.setdefault("gates", {})["GATES"] = [
            {
                "gate": _number(record.get("gate")),
                "week": _number(record.get("week")),
                "criteria": record.get("criteria", ""),
                "remediation": record.get("remediation", ""),
            }
            for record in sorted(gates, key=lambda item: _number(item.get("gate")))
        ]

    # Transitional entity overlays.  These adapters let a schema edit flow
    # through even while older entity files still contain a few legacy rows
    # with incomplete IDs; the generated snapshot supplies fields that the
    # first schema migration did not model yet.
    def merge_rows(module: str, export: str, rows: list[dict[str, Any]], key: str, fields: dict[str, str]) -> None:
        targets = effective.get(module, {}).get(export, [])
        if not isinstance(targets, list):
            return
        by_key = {str(item.get(key)): item for item in targets if isinstance(item, dict) and item.get(key) is not None}
        for row in rows:
            source_key = row.get("id")
            if source_key is None:
                continue
            source_key = str(source_key)
            target = by_key.get(source_key)
            if target is None:
                continue
            for source_field, target_field in fields.items():
                if source_field in row and row[source_field] is not None:
                    target[target_field] = row[source_field]

    agents_schema = _records(_load_yaml(SCHEMA_DIR / "agents.yaml"))
    _apply_agent_schema_overrides(effective, agents_schema)

    for row in agents_schema:
        if row.get("id") == "project-manus" and isinstance(effective.get("agents", {}).get("MANUS_CAPSTONE"), dict):
            target = effective["agents"]["MANUS_CAPSTONE"]
            for source_field, target_field in {
                "title": "title", "vision": "vision", "architecture": "architecture", "features": "features",
                "learning_focus": "learningFocus", "challenges": "challenges", "evaluation": "evaluation",
                "extensions": "extensions", "stack": "stack",
            }.items():
                if source_field in row and row[source_field] not in (None, "", []):
                    target[target_field] = row[source_field]

    mandala_rows = _records(_load_yaml(SCHEMA_DIR / "mandalas.yaml"))
    for row in mandala_rows:
        identifier = str(row.get("id", ""))
        if not identifier.startswith("mandala-") or identifier == "mandala-":
            continue
        merge_rows(
            "mandalas",
            "MANDALAS",
            [{**row, "id": identifier.removeprefix("mandala-")}],
            "id",
            {"id": "id", "title": "title", "days": "days", "weeks": "weeks", "identity": "identity", "topics": "topics", "evidence": "evidence", "transformation": "transformation"},
        )

    engineering_schema = _records(_load_yaml(SCHEMA_DIR / "engineering.yaml"))
    merge_rows(
        "engineering",
        "ENGINEERING_TASKS",
        [{**row, "id": str(row.get("number"))} for row in engineering_schema if str(row.get("id", "")).startswith("eng-task-") and row.get("number") is not None and row.get("title")],
        "n",
        {"title": "title"},
    )
    merge_rows(
        "engineering",
        "PRACTICE_EXERCISES",
        [{**row, "id": str(row.get("number"))} for row in engineering_schema if row.get("number") is not None and row.get("id", "").startswith("practice-")],
        "n",
        {"title": "title"},
    )

    design_schema = _records(_load_yaml(SCHEMA_DIR / "system_design.yaml"))
    merge_rows(
        "systemDesign",
        "DESIGN_WEEKS",
        [{**row, "id": str(row.get("week"))} for row in design_schema if row.get("week") is not None and row.get("topic")],
        "week",
        {"topic": "topic", "case_lab": "caseLab", "evidence": "evidence"},
    )
    math_schema = _records(_load_yaml(SCHEMA_DIR / "math.yaml"))
    merge_rows(
        "math",
        "MATH_TRACKS",
        [{**row, "id": str(row.get("track_number"))} for row in math_schema if row.get("track_number") is not None and row.get("name")],
        "id",
        {"name": "name", "range": "range", "description": "description", "modules": "modules"},
    )

    interview_schema = _records(_load_yaml(SCHEMA_DIR / "interview.yaml"))
    merge_rows(
        "interview",
        "CARL_STORIES",
        [{**row, "id": row.get("story")} for row in interview_schema if row.get("story")],
        "story",
        {"story": "story", "weeks": "weeks"},
    )
    # Remaining interview exports have stable natural keys in the schema.
    interview_target = effective.get("interview", {})
    for row in interview_schema:
        identifier = str(row.get("id", ""))
        if identifier == "interview-weekly-minimums" and isinstance(row.get("rules"), list):
            interview_target["WEEKLY_MINIMUMS"] = list(row["rules"])
        elif identifier.startswith("interview-focus-") and row.get("weeks"):
            for target in interview_target.get("INTERVIEW_FOCUS", []):
                if target.get("weeks") == row["weeks"]:
                    target.update({"focus": row.get("focus", target.get("focus", ""))})
        elif identifier.startswith("roadmap-track-") and row.get("name"):
            for target in interview_target.get("ROADMAP_TRACKS", []):
                if target.get("name") == row["name"]:
                    target.update({"count": row.get("count", target.get("count", 0)), "items": row.get("items", target.get("items", []))})
        elif identifier.startswith("capstone-req-") and row.get("area"):
            for target in interview_target.get("CAPSTONE_REQUIREMENTS", []):
                if target.get("area") == row["area"]:
                    target["requirement"] = row.get("requirement", target.get("requirement", ""))
        elif identifier.startswith("completion-level-") and row.get("level"):
            for target in interview_target.get("COMPLETION_LEVELS", []):
                if target.get("level") == row["level"]:
                    target["requires"] = row.get("requires", target.get("requires", ""))

    prereq_schema = _records(_load_yaml(SCHEMA_DIR / "prerequisites.yaml"))
    merge_rows(
        "prerequisites",
        "PREREQUISITE_RESOURCES",
        [{**row, "id": row.get("title")} for row in prereq_schema if row.get("title") and row.get("url")],
        "title",
        {"title": "title", "url": "url", "focus": "focus", "weeks": "weeks", "outcome": "outcome"},
    )
    for row in prereq_schema:
        if row.get("id", "").startswith("prereq-plan-") and row.get("weeks"):
            for target in effective.get("prerequisites", {}).get("PREREQUISITE_36_WEEKS", []):
                if target.get("weeks") == row["weeks"]:
                    target.update({
                        "title": row.get("title", target.get("title", "")),
                        "resources": row.get("resources", target.get("resources", [])),
                        "outcome": row.get("outcome", target.get("outcome", "")),
                    })

    # Deep dives are a clean one-to-one entity when present.  The source view
    # already has the exact typed shape, so use the YAML only for scalar
    # metadata and retain artifact details if an older schema omits them.
    deep_schema = _records(_load_yaml(SCHEMA_DIR / "deep_dives.yaml"))
    if deep_schema and "deepDives" in effective:
        track = next((r for r in deep_schema if r.get("id") == "tool_recommendation_systems"), None)
        if track:
            current = effective["deepDives"].get("TOOL_RECOMMENDATION_SYSTEMS")
            if isinstance(current, dict):
                for key in ("id", "title", "shortName", "parallelTrack", "pairEnforcement", "tier", "level", "seam", "selectionRationale"):
                    yaml_key = {"selectionRationale": "selection_rationale", "shortName": "short_name", "parallelTrack": "parallel_track", "pairEnforcement": "pair_enforcement"}.get(key, key)
                    if yaml_key in track:
                        current[key] = track[yaml_key]
                ref_map = {"selection_rationale": "selectionRationale", "size_kb": "sizeKb", "section_count": "sectionCount", "pair_id": "pairId", "pair_role": "pairRole", "prerequisite_of": "prerequisiteOf"}
                for artifact in _records(track.get("primary_artifacts")):
                    target_artifact = next((item for item in current.get("primaryArtifacts", []) if isinstance(item, dict) and item.get("id") == artifact.get("id")), None)
                    if target_artifact is None:
                        continue
                    for source_key, target_key in ref_map.items():
                        if source_key in artifact:
                            target_artifact[target_key] = artifact[source_key]
                    for key in ("id", "title", "path", "tier", "level"):
                        if key in artifact:
                            target_artifact[key] = artifact[key]

    return effective


# ---------------------------------------------------------------------------
# TypeScript rendering
# ---------------------------------------------------------------------------


def _quote(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return "'" + escaped + "'"


def _js(value: Any, indent: int = 0) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return _quote(value)
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        rendered = [_js(item, indent + 2) for item in value]
        # Keep simple object arrays readable and stable, one item per line.
        if all(len(item) < 240 and "\n" not in item for item in rendered):
            return "[" + ", ".join(rendered) + "]"
        pad = " " * (indent + 2)
        close = " " * indent
        return "[\n" + "\n".join(f"{pad}{item}," for item in rendered) + f"\n{close}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rendered = [f"{key}: {_js(item, indent + 2)}" for key, item in value.items()]
        if all(len(item) < 240 and "\n" not in item for item in rendered):
            return "{ " + ", ".join(rendered) + " }"
        pad = " " * (indent + 2)
        close = " " * indent
        return "{\n" + "\n".join(f"{pad}{item}," for item in rendered) + f"\n{close}}}"
    raise GenerationError(f"cannot render value of type {type(value).__name__}")


def _render_module(path: Path, values: dict[str, Any]) -> str:
    original = path.read_text(encoding="utf-8")
    declarations = _const_expressions(original)
    replacements: list[tuple[int, int, str]] = []
    current_values = _literal_values(original)
    for name, value in values.items():
        declaration = declarations.get(name)
        if declaration is None:
            continue
        start, end, expression = declaration
        if not expression.startswith(("[", "{")):
            continue
        # Avoid churn when the schema and the current view are already equal.
        if current_values.get(name) == value:
            continue
        replacements.append((start, end, _js(value)))

    rendered = original
    for start, end, replacement in reversed(replacements):
        rendered = rendered[:start] + replacement + rendered[end:]
    if not rendered.startswith(GENERATED_HEADER):
        rendered = GENERATED_HEADER + rendered
    return rendered


# ---------------------------------------------------------------------------
# Cookiecutter view
# ---------------------------------------------------------------------------


def _week_range(value: str) -> tuple[int, int]:
    numbers = [int(number) for number in re.findall(r"\d+", str(value))]
    if len(numbers) < 2:
        raise GenerationError(f"invalid week range: {value!r}")
    return numbers[0], numbers[1]


def _python(value: Any) -> str:
    return pprint.pformat(value, width=110, sort_dicts=False, compact=False)


def _hook_values(effective: dict[str, dict[str, Any]], cookie: dict[str, Any]) -> dict[str, Any]:
    weeks = effective.get("weeks", {})
    phases = weeks.get("PHASES", [])
    week_rows = weeks.get("WEEKS", [])
    phase_lists: dict[int, list[tuple[Any, ...]]] = {}
    for phase in phases:
        number = int(phase["id"])
        phase_lists[number] = [
            (
                int(row["week"]),
                row.get("module", ""),
                row.get("focus", ""),
                row.get("deliverable", ""),
            )
            for row in week_rows
            if int(row["week"]) >= int(phase["start"]) and int(row["week"]) <= int(phase["end"])
        ]

    phase_constants = {f"PHASE_{number}": rows for number, rows in sorted(phase_lists.items())}
    phase_tuples = [
        (
            f"{int(phase['id']) - 1:02d}",
            phase.get("theme", ""),
            int(phase["start"]),
            int(phase["end"]),
            phase_lists.get(int(phase["id"]), []),
        )
        for phase in sorted(phases, key=lambda item: int(item["id"]))
    ]

    gate_schema = _records(_load_yaml(SCHEMA_DIR / "gates.yaml"))
    # Keep canonical IDs in the adapter so the rendered cookiecutter hook can
    # validate AGENTS.md without copying the source schema into learner repos.
    # Week IDs are schema IDs (week-001), while gate IDs retain gate-1 style;
    # GATE_WEEKS supplies the useful gate -> exit-week relationship.
    week_ids = tuple(
        str(record["id"])
        for record in sorted(
            _records(_load_yaml(SCHEMA_DIR / "weeks.yaml")),
            key=lambda item: int(_number(item.get("week", 0)))
            if item.get("week") is not None
            else -1,
        )
        if _valid_id(record, "week-") and record.get("week") is not None
    )
    gate_records = [
        record
        for record in gate_schema
        if _valid_id(record, "gate-") and record.get("gate") is not None
    ]
    gate_ids = tuple(
        str(record["id"])
        for record in sorted(gate_records, key=lambda item: int(_number(item["gate"])))
    )
    gate_weeks = {
        str(record["id"]): int(_number(record["week"]))
        for record in sorted(gate_records, key=lambda item: int(_number(item["gate"])))
        if record.get("week") is not None
    }
    programs = [record for record in gate_schema if record.get("release_week") is not None]
    program_tuples = [
        (
            str(record.get("id", "")),
            record.get("name", ""),
            _week_range(record.get("weeks", "W0–0"))[0],
            _week_range(record.get("weeks", "W0–0"))[1],
            record.get("release", ""),
        )
        for record in sorted(programs, key=lambda item: int(item.get("release_week", 0)))
    ]
    releases = [
        (
            int(record.get("release_week")),
            record.get("name", ""),
            "Weeks " + str(record.get("weeks", "")).removeprefix("W").replace("–", "-"),
            record.get("release", ""),
            int(record.get("release_week")),
        )
        for record in sorted(programs, key=lambda item: int(item.get("release_week", 0)))
    ]

    forge_rows = _records(_load_yaml(SCHEMA_DIR / "forge.yaml"))
    forge_lanes = []
    for row in forge_rows:
        if not str(row.get("id", "")).startswith("forge-lane-"):
            continue
        start, end = _week_range(row.get("weeks", ""))
        tier = row.get("tier", "Core")
        timebox = "2-3 hr" if "Boss" in str(tier) else ("45-120 min" if "Supporting" in str(tier) else "45-90 min")
        forge_lanes.append((start, end, tier, row.get("theme", ""), row.get("artifact", ""), timebox))

    forge_bosses: dict[int, tuple[str, str, str, str]] = {}
    for row in effective.get("forge", {}).get("FORGE_BOSSES", []):
        name = str(row.get("name", ""))
        numbers = re.findall(r"\d+", name)
        if not numbers:
            continue
        week = int(numbers[-1])
        title = re.sub(r"^(?:Weeks?|Week)\s+\d+(?:[–-]\d+)?\s*(?:optional\s*)?—\s*", "", name)
        forge_bosses[week] = ("Boss fight", title, row.get("description", ""), "2-3 hr")

    agents = effective.get("agents", {}).get("AGENT_MODULES", [])
    agent_modules = [
        (str(row.get("id", "")), row.get("title", ""), tuple(row.get("topics", []) or []))
        for row in agents
        if row.get("id") is not None
    ]
    bridges = effective.get("agents", {}).get("AGENT_BRIDGES", [])
    agent_bridges = [
        (
            str(row.get("module", "")),
            row.get("title", ""),
            row.get("gap", ""),
            tuple((item.get("concept", ""), item.get("weeks", ""), item.get("insight", "")) for item in row.get("rows", []) or []),
        )
        for row in bridges
    ]
    bridge_summary = [
        (row.get("module", ""), row.get("weeks", ""))
        for row in effective.get("agents", {}).get("BRIDGE_SUMMARY", [])
    ]
    pitch = effective.get("agents", {}).get("BRIDGE_PITCH", {}) or {}
    manus = effective.get("agents", {}).get("MANUS_CAPSTONE", {}) or {}
    manus_tuple = (
        manus.get("title", ""),
        manus.get("vision", ""),
        tuple(manus.get("features", []) or []),
        tuple(manus.get("architecture", []) or []),
        manus.get("learningFocus", ""),
        tuple(manus.get("challenges", []) or []),
        tuple(manus.get("evaluation", []) or []),
        tuple(manus.get("extensions", []) or []),
        ", ".join(manus.get("stack", []) or []) if isinstance(manus.get("stack"), list) else manus.get("stack", ""),
    )

    resources = effective.get("resources", {})
    mandalas = effective.get("mandalas", {}).get("MANDALAS", [])
    prereq = effective.get("prerequisites", {})
    cookie = cookie or {}
    values: dict[str, Any] = {}
    values.update(phase_constants)
    values.update(
        {
            "PHASES": phase_tuples,
            "WEEK_IDS": week_ids,
            "GATE_IDS": gate_ids,
            "GATE_WEEKS": gate_weeks,
            "PROGRAMS": program_tuples,
            "RECOVERY_AFTER": weeks.get("RECOVERY_AFTER", []),
            "RELEASES": releases,
            "FORGE_LANES": forge_lanes,
            "FORGE_BOSSES": forge_bosses,
            "ENGINEERING_PRIMITIVES": cookie.get("ENGINEERING_PRIMITIVES", []),
            "INTERVIEW_DRILLS": cookie.get("INTERVIEW_DRILLS", []),
            "SYSTEM_DESIGN_WEEKS": [
                (
                    int(row.get("week")),
                    row.get("topic", ""),
                    row.get("caseLab", ""),
                    row.get("evidence", ""),
                )
                for row in effective.get("systemDesign", {}).get("DESIGN_WEEKS", [])
            ],
            "DARBAR_TOTAL": cookie.get("DARBAR_TOTAL", 0),
            "DARBAR_DIFFICULTIES": cookie.get("DARBAR_DIFFICULTIES", ""),
            "DARBAR_CATEGORIES": tuple(cookie.get("DARBAR_CATEGORIES", ())),
            "PREREQUISITES": [
                (row.get("weeks", ""), row.get("title", ""), row.get("url", ""), row.get("focus", ""), row.get("outcome", ""))
                for row in prereq.get("PREREQUISITE_RESOURCES", [])
            ],
            "PREREQ_PLAN": [
                (
                    row.get("weeks", ""),
                    row.get("title", ""),
                    " · ".join(row.get("resources", []) or []) if isinstance(row.get("resources"), list) else row.get("resources", ""),
                    row.get("outcome", ""),
                )
                for row in prereq.get("PREREQUISITE_36_WEEKS", [])
            ],
            "AGENT_MODULES_CC": agent_modules,
            "AGENT_BRIDGE_CC": agent_bridges,
            "BRIDGE_SUMMARY_CC": bridge_summary,
            "BRIDGE_PITCH_QUOTE": pitch.get("quote", ""),
            "BRIDGE_PITCH_TAG": pitch.get("tag", ""),
            "MANUS_CAPSTONE_CC": manus_tuple,
            "AGENT_PAPERS_CC": [
                (row.get("paper", ""), row.get("venue", ""), row.get("topic", ""), row.get("url", ""))
                for row in resources.get("AGENT_PAPERS", [])
            ],
            "AGENT_PAPER_WEEKS": cookie.get("AGENT_PAPER_WEEKS", {}),
            "MANDALAS_CC": [
                (
                    str(row.get("id", "")),
                    row.get("title", ""),
                    row.get("weeks", ""),
                    row.get("identity", ""),
                    row.get("transformation", ""),
                )
                for row in mandalas
                if row.get("id") is not None
            ],
        }
    )
    return values


def _render_hook_module(values: dict[str, Any]) -> str:
    names = sorted(values)
    chunks = [
        '"""Generated cookiecutter curriculum constants.\n\nDO NOT EDIT: run ``python tools/generate.py`` after changing schema/*.yaml.\n"""',
        "from __future__ import annotations",
        "",
    ]
    for name in names:
        chunks.append(f"{name} = {_python(values[name])}")
        chunks.append("")
    chunks.append(f"__all__ = {_python(names)}")
    chunks.append("")
    return "\n".join(chunks)


# ---------------------------------------------------------------------------
# Generated-output hash manifest
# ---------------------------------------------------------------------------


def _generated_paths() -> list[Path]:
    return sorted(DATA_DIR.glob("*.ts")) + [GENERATED_HOOK, TEMPLATE_GENERATED_HOOK]


def _hash_outputs() -> dict[str, dict[str, Any]]:
    files: dict[str, dict[str, Any]] = {}
    for path in _generated_paths():
        if not path.exists():
            raise GenerationError(f"missing generated output: {path.relative_to(REPO_ROOT)}")
        payload = path.read_bytes()
        files[str(path.relative_to(REPO_ROOT))] = {
            "sha256": hashlib.sha256(payload).hexdigest(),
            "bytes": len(payload),
        }
    return {"algorithm": "sha256", "files": files}


def _write_hash_manifest() -> None:
    HASH_MANIFEST.write_text(
        json.dumps(_hash_outputs(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _check_hash_manifest() -> None:
    if not HASH_MANIFEST.exists():
        raise GenerationError(f"missing {HASH_MANIFEST.relative_to(REPO_ROOT)}")
    try:
        expected = json.loads(HASH_MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise GenerationError(f"invalid {HASH_MANIFEST.relative_to(REPO_ROOT)}: {error}") from error
    actual = _hash_outputs()
    if expected != actual:
        raise GenerationError("generated_hashes.json does not match generated outputs")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate(*, check: bool = False) -> list[Path]:
    _validate_curriculum_schema()
    source = _source_data()
    effective = _apply_schema_overrides(source)
    cookie = _load_yaml(COOKIECUTTER_SCHEMA)
    changed: list[Path] = []

    for module, values in sorted(effective.items()):
        path = DATA_DIR / f"{module}.ts"
        if not path.exists():
            continue
        rendered = _render_module(path, values)
        current = path.read_text(encoding="utf-8")
        if rendered != current:
            changed.append(path)
            if not check:
                path.write_text(rendered, encoding="utf-8")

    hook_rendered = _render_hook_module(_hook_values(effective, cookie))
    for hook_path in (GENERATED_HOOK, TEMPLATE_GENERATED_HOOK):
        current_hook = hook_path.read_text(encoding="utf-8") if hook_path.exists() else ""
        if hook_rendered != current_hook:
            changed.append(hook_path)
            if not check:
                hook_path.parent.mkdir(parents=True, exist_ok=True)
                hook_path.write_text(hook_rendered, encoding="utf-8")

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    parser.add_argument(
        "--update-hashes",
        action="store_true",
        help="write tools/generated_hashes.json after generating outputs",
    )
    args = parser.parse_args(argv)
    if args.check and args.update_hashes:
        parser.error("--check and --update-hashes are mutually exclusive")
    try:
        changed = generate(check=args.check)
        if args.check and not changed:
            _check_hash_manifest()
    except (OSError, GenerationError, yaml.YAMLError) as error:
        print(f"generate.py: error: {error}", file=sys.stderr)
        return 1
    if args.update_hashes:
        _write_hash_manifest()
    if changed:
        action = "would update" if args.check else "updated"
        print(f"generate.py: {action} {len(changed)} file(s):")
        for path in changed:
            print(f"  - {path.relative_to(REPO_ROOT)}")
        return 1 if args.check else 0
    print("generate.py: generated views are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
