"""Generate typed capstone site data from ``schema/capstones.yaml``.

The main curriculum generator intentionally knows only about the legacy
entity registries.  Capstone artifacts are a small, heterogeneous catalog, so
this focused generator keeps their validation and rendering isolated.  It
updates the generated TypeScript data module and the marked failure-matrix
block in the Capstone 3 Markdown spec while leaving all surrounding prose
untouched.

Usage::

    python tools/generate_capstones.py          # write generated artifacts
    python tools/generate_capstones.py --check  # report drift without writing
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "capstones.yaml"
DATA_PATH = REPO_ROOT / "src" / "data" / "capstones.ts"
CAPSTONE3_MARKDOWN = REPO_ROOT / "CAPSTONE3_OPENROUTER.md"

MARKER_START = "<!-- generated: capstone-3-failure-matrix:start -->"
MARKER_END = "<!-- generated: capstone-3-failure-matrix:end -->"
GENERATED_HEADER = "// @generated by tools/generate_capstones.py; edit schema/capstones.yaml instead.\n"

EXPECTED_IDS = ("capstone-1", "capstone-2", "capstone-3")
COMMON_FIELDS = (
    "id",
    "number",
    "slug",
    "kind",
    "chip",
    "chip_class",
    "title",
    "subtitle",
    "weeks",
    "image",
    "description",
    "points",
    "prose_source",
    "artifact_type",
)


class CapstoneGenerationError(ValueError):
    """Raised when the capstone schema cannot safely produce site artifacts."""


def _schema_error(message: str) -> CapstoneGenerationError:
    return CapstoneGenerationError(f"schema/capstones.yaml: {message}")


def _records(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        raise _schema_error("top-level value must be a list of records")
    if not all(isinstance(item, dict) for item in value):
        bad = next(index for index, item in enumerate(value) if not isinstance(item, dict))
        raise _schema_error(f"record {bad} must be a mapping")
    return value


def load_capstones(path: Path = SCHEMA_PATH) -> list[dict[str, Any]]:
    """Load and validate the three capstone records.

    Validation lives here rather than in the generic generator so the
    heterogeneous structured artifacts remain explicit and easy to review.
    ``load_capstones`` is intentionally public for focused tests and other
    tooling that needs the canonical data.
    """
    try:
        with path.open(encoding="utf-8") as handle:
            loaded = yaml.safe_load(handle)
    except FileNotFoundError as error:
        raise CapstoneGenerationError(f"missing {path.relative_to(REPO_ROOT)}") from error
    except yaml.YAMLError as error:
        raise CapstoneGenerationError(f"invalid YAML: {error}") from error

    records = _records(loaded)
    if len(records) != len(EXPECTED_IDS):
        raise _schema_error(f"expected exactly {len(EXPECTED_IDS)} capstones, found {len(records)}")

    ids = [record.get("id") for record in records]
    if tuple(ids) != EXPECTED_IDS:
        raise _schema_error(f"records must be ordered {EXPECTED_IDS!r}, found {tuple(ids)!r}")
    if len(set(ids)) != len(ids):  # defensive: this also gives a useful error if ordering changes later
        raise _schema_error("capstone IDs must be unique")

    for index, record in enumerate(records):
        missing = [field for field in COMMON_FIELDS if field not in record]
        if missing:
            raise _schema_error(f"{record.get('id', index)} is missing required field(s): {', '.join(missing)}")
        if not isinstance(record["number"], int) or record["number"] != index + 1:
            raise _schema_error(f"{record['id']} number must be {index + 1}")
        if not isinstance(record["points"], list) or not record["points"]:
            raise _schema_error(f"{record['id']} points must be a non-empty list")
        source = REPO_ROOT / str(record["prose_source"])
        if not source.exists():
            raise _schema_error(f"{record['id']} prose_source does not exist: {record['prose_source']!r}")

    first, second, third = records
    _require_list(first, "events", "capstone-1")
    _require_list(first, "queries", "capstone-1")
    _require_list(first, "expected", "capstone-1")
    if len(first["events"]) != 6 or len(first["queries"]) != 2 or len(first["expected"]) != 2:
        raise _schema_error("capstone-1 example must contain 6 events, 2 queries, and 2 expected rows")
    for event in first["events"]:
        _require_mapping(event, "capstone-1.events")
        _require_keys(event, ("model_id", "is_error", "tokens"), "capstone-1.events")
    for query in first["queries"]:
        if not isinstance(query, list) or len(query) != 2 or not all(isinstance(value, int) for value in query):
            raise _schema_error("capstone-1 queries must be [left, right] integer pairs")
    for expected in first["expected"]:
        _require_mapping(expected, "capstone-1.expected")
        _require_keys(expected, ("top_error_model", "count", "distinct", "wasted"), "capstone-1.expected")

    _require_mapping(second.get("tree"), "capstone-2.tree")
    _require_keys(second["tree"], ("root", "nodes", "children"), "capstone-2.tree")
    _require_list(second, "queries", "capstone-2")
    _require_list(second, "expected", "capstone-2")
    nodes = second["tree"]["nodes"]
    if not isinstance(nodes, list) or not nodes:
        raise _schema_error("capstone-2.tree.nodes must be a non-empty list")
    for node in nodes:
        _require_mapping(node, "capstone-2.tree.nodes")
        _require_keys(node, ("id", "tool_id", "is_error", "tokens"), "capstone-2.tree.nodes")
    children = second["tree"]["children"]
    if not isinstance(children, list) or len(children) != len(nodes):
        raise _schema_error("capstone-2.tree.children must have one list per node")
    if len(second["queries"]) != len(second["expected"]):
        raise _schema_error("capstone-2 queries and expected rows must have equal lengths")
    for expected in second["expected"]:
        _require_mapping(expected, "capstone-2.expected")
        _require_keys(expected, ("top_error_tool", "top_error_count", "distinct_error_tools", "wasted_tokens"), "capstone-2.expected")

    _require_list(third, "promises", "capstone-3")
    _require_list(third, "failure_matrix", "capstone-3")
    _require_list(third, "interview_questions", "capstone-3")
    _require_mapping(third.get("rubric"), "capstone-3.rubric")
    if len(third["failure_matrix"]) != 10:
        raise _schema_error("capstone-3 failure_matrix must contain 10 rows")
    for row in third["failure_matrix"]:
        _require_mapping(row, "capstone-3.failure_matrix")
        _require_keys(row, ("id", "failure", "expected_behavior"), "capstone-3.failure_matrix")
    if len(third["interview_questions"]) != 7:
        raise _schema_error("capstone-3 interview_questions must contain 7 questions")
    _require_keys(third["rubric"], ("points", "dimensions", "scoring", "passing"), "capstone-3.rubric")
    if third["rubric"]["points"] != 24 or len(third["rubric"]["dimensions"]) != 12:
        raise _schema_error("capstone-3 rubric must contain 24 points across 12 dimensions")

    return records


def _require_mapping(value: Any, label: str) -> None:
    if not isinstance(value, dict):
        raise _schema_error(f"{label} must be a mapping")


def _require_list(record: dict[str, Any], field: str, label: str) -> None:
    if not isinstance(record.get(field), list):
        raise _schema_error(f"{label}.{field} must be a list")


def _require_keys(value: dict[str, Any], keys: tuple[str, ...], label: str) -> None:
    missing = [key for key in keys if key not in value]
    if missing:
        raise _schema_error(f"{label} is missing required field(s): {', '.join(missing)}")


def _camel_key(key: str) -> str:
    return re.sub(r"_([a-zA-Z0-9])", lambda match: match.group(1).upper(), key)


def _camelize(value: Any) -> Any:
    """Convert YAML's snake_case keys to the camelCase site-data contract."""
    if isinstance(value, dict):
        return {_camel_key(str(key)): _camelize(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_camelize(item) for item in value]
    return value


def _json(value: Any) -> str:
    # JSON is a strict subset of TypeScript literals and gives deterministic
    # quoting/escaping without requiring a Node dependency.
    return json.dumps(value, ensure_ascii=False, indent=2, separators=(",", ": "))


def render_typescript(records: list[dict[str, Any]] | None = None) -> str:
    """Render the typed site module from validated YAML records."""
    records = load_capstones() if records is None else records
    data = _camelize(records)
    return (
        GENERATED_HEADER
        + """/**
 * Structured capstone cards and examples.
 *
 * The narrative remains in CAPSTONE*.md; this module is generated from
 * schema/capstones.yaml for Astro pages and artifact-level checks.
 */

export interface CapstoneEvent {
  modelId: number;
  isError: boolean;
  tokens: number;
}

export interface CapstoneExpected {
  [key: string]: number;
}

export interface CapstoneTreeNode {
  id: number;
  toolId: number;
  isError: boolean;
  tokens: number;
}

export interface CapstoneTree {
  root: number;
  nodes: CapstoneTreeNode[];
  children: number[][];
}

export interface CapstoneFailure {
  id: string;
  failure: string;
  expectedBehavior: string;
}

export interface CapstonePromise {
  label: string;
  desc: string;
}

export interface CapstoneRubric {
  points: number;
  dimensions: string[];
  scoring: string;
  passing: string;
}

export interface Capstone {
  id: string;
  number: number;
  slug: string;
  kind: string;
  chip: string;
  chipClass: string;
  title: string;
  subtitle: string;
  weeks: string;
  image: string;
  description: string;
  points: string[];
  proseSource: string;
  artifactType: string;
  events?: CapstoneEvent[];
  queries?: number[][];
  expected?: CapstoneExpected[];
  tree?: CapstoneTree;
  promises?: CapstonePromise[];
  failureMatrix?: CapstoneFailure[];
  interviewQuestions?: string[];
  rubric?: CapstoneRubric;
}

export const CAPSTONES: Capstone[] = """
        + _json(data)
        + ";\n\n"
        + "export const CAPSTONE_1: Capstone = CAPSTONES[0]!;\n"
        + "export const CAPSTONE_2: Capstone = CAPSTONES[1]!;\n"
        + "export const CAPSTONE_3: Capstone = CAPSTONES[2]!;\n"
    )


def render_failure_matrix_markdown(capstone: dict[str, Any] | None = None) -> str:
    """Render only the marked Capstone 3 table, preserving prose around it."""
    records = load_capstones()
    capstone = capstone or records[2]
    rows = capstone["failure_matrix"]
    lines = [MARKER_START, "", "| Failure | Expected behavior |", "|---|---|"]
    lines.extend(f"| {row['failure']} | {row['expected_behavior']} |" for row in rows)
    lines.extend(["", MARKER_END])
    return "\n".join(lines)


def _replace_marked_block(text: str, replacement: str) -> str:
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
        re.DOTALL,
    )
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise CapstoneGenerationError(
            f"{CAPSTONE3_MARKDOWN.relative_to(REPO_ROOT)} must contain exactly one marked failure-matrix block"
        )
    return text[: matches[0].start()] + replacement + text[matches[0].end() :]


def _render_markdown_from_schema(records: list[dict[str, Any]]) -> str:
    try:
        current = CAPSTONE3_MARKDOWN.read_text(encoding="utf-8")
    except FileNotFoundError as error:
        raise CapstoneGenerationError(f"missing {CAPSTONE3_MARKDOWN.relative_to(REPO_ROOT)}") from error
    return _replace_marked_block(current, render_failure_matrix_markdown(records[2]))


def generate(*, check: bool = False) -> list[Path]:
    """Write generated outputs or return changed paths in ``check`` mode."""
    records = load_capstones()
    expected_ts = render_typescript(records)
    expected_md = _render_markdown_from_schema(records)
    changed: list[Path] = []

    current_ts = DATA_PATH.read_text(encoding="utf-8") if DATA_PATH.exists() else None
    if current_ts != expected_ts:
        changed.append(DATA_PATH)
        if not check:
            DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
            DATA_PATH.write_text(expected_ts, encoding="utf-8")

    current_md = CAPSTONE3_MARKDOWN.read_text(encoding="utf-8")
    if current_md != expected_md:
        changed.append(CAPSTONE3_MARKDOWN)
        if not check:
            CAPSTONE3_MARKDOWN.write_text(expected_md, encoding="utf-8")

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args(argv)
    try:
        changed = generate(check=args.check)
    except (OSError, CapstoneGenerationError, yaml.YAMLError) as error:
        print(f"generate_capstones.py: error: {error}", file=sys.stderr)
        return 1
    if args.check and changed:
        print("generate_capstones.py: generated outputs are stale:", file=sys.stderr)
        for path in changed:
            print(f"  - {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    if changed:
        for path in changed:
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    else:
        print("generate_capstones.py: outputs are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
