// @generated by tools/generate_capstones.py; edit schema/capstones.yaml instead.
/**
 * Structured capstone cards and examples.
 *
 * The narrative remains in CAPSTONE*.md; this module is generated from
 * schema/capstones.yaml for Astro pages and artifact-level checks.
 */

export interface CapstoneEvent {
  modelId: number;
  isError: boolean;
  tokens: number;
}

export interface CapstoneExpected {
  [key: string]: number;
}

export interface CapstoneTreeNode {
  id: number;
  toolId: number;
  isError: boolean;
  tokens: number;
}

export interface CapstoneTree {
  root: number;
  nodes: CapstoneTreeNode[];
  children: number[][];
}

export interface CapstoneFailure {
  id: string;
  failure: string;
  expectedBehavior: string;
}

export interface CapstonePromise {
  label: string;
  desc: string;
}

export interface CapstoneRubric {
  points: number;
  dimensions: string[];
  scoring: string;
  passing: string;
}

export interface Capstone {
  id: string;
  number: number;
  slug: string;
  kind: string;
  chip: string;
  chipClass: string;
  title: string;
  subtitle: string;
  weeks: string;
  image: string;
  description: string;
  points: string[];
  proseSource: string;
  artifactType: string;
  events?: CapstoneEvent[];
  queries?: number[][];
  expected?: CapstoneExpected[];
  tree?: CapstoneTree;
  promises?: CapstonePromise[];
  failureMatrix?: CapstoneFailure[];
  interviewQuestions?: string[];
  rubric?: CapstoneRubric;
}

export const CAPSTONES: Capstone[] = [
  {
    "id": "capstone-1",
    "number": 1,
    "slug": "trace-forensics",
    "kind": "required",
    "chip": "Required",
    "chipClass": "chip--ok",
    "title": "Capstone 1 - Multi-Tenant LLM Trace Forensics",
    "subtitle": "Mo's Algorithm over immutable trace segments",
    "weeks": "Weeks 103–108",
    "image": "/images/capstone_trace_forensics_infographic.webp",
    "description": "A staff-level system design + coding capstone. Build the observability and forensics platform for a large multi-tenant LLM gateway, then answer exact batch forensic queries over immutable event segments with Mo's algorithm. The required algorithmic capstone.",
    "points": [
      "High-throughput ingestion, PII safety",
      "Immutable segments, watermarks, correction deltas",
      "Mo's algorithm + frequency buckets",
      "Exact vs approximate mergeability",
      "24-point self-grading rubric"
    ],
    "proseSource": "CAPSTONE.md",
    "artifactType": "mos_range_query",
    "events": [
      {
        "modelId": 1,
        "isError": true,
        "tokens": 100
      },
      {
        "modelId": 2,
        "isError": false,
        "tokens": 50
      },
      {
        "modelId": 1,
        "isError": true,
        "tokens": 200
      },
      {
        "modelId": 3,
        "isError": true,
        "tokens": 10
      },
      {
        "modelId": 2,
        "isError": true,
        "tokens": 70
      },
      {
        "modelId": 1,
        "isError": false,
        "tokens": 10
      }
    ],
    "queries": [
      [
        0,
        4
      ],
      [
        1,
        5
      ]
    ],
    "expected": [
      {
        "topErrorModel": 1,
        "count": 2,
        "distinct": 3,
        "wasted": 380
      },
      {
        "topErrorModel": 2,
        "count": 1,
        "distinct": 2,
        "wasted": 80
      }
    ]
  },
  {
    "id": "capstone-2",
    "number": 2,
    "slug": "tree-forensics",
    "kind": "optional",
    "chip": "Boss fight",
    "chipClass": "chip--amber",
    "title": "Capstone 2 - Agent Execution Forensics",
    "subtitle": "Euler Tour + DSU on Tree",
    "weeks": "Week 108 · optional",
    "image": "/images/capstone_tree_nightmare_forensics.webp",
    "description": "The optional Week 108 boss fight. If Capstone 1 was forensics over a flat log, this is forensics over a forest of agent execution trees. Combine systems design with esoteric tree algorithms for exact subtree queries.",
    "points": [
      "Forest assembly, reorder buffers, cycle detection",
      "Euler Tour to flatten subtree → range",
      "DSU on Tree (sack / keep-heavy)",
      "Reversible aggregates + mode tie-breaks",
      "Not required for the LLM Platform badge"
    ],
    "proseSource": "CAPSTONE2_EULER_DSU.md",
    "artifactType": "euler_dsu_subtree_query",
    "tree": {
      "root": 0,
      "nodes": [
        {
          "id": 0,
          "toolId": 1,
          "isError": true,
          "tokens": 100
        },
        {
          "id": 1,
          "toolId": 2,
          "isError": false,
          "tokens": 50
        },
        {
          "id": 2,
          "toolId": 1,
          "isError": true,
          "tokens": 200
        },
        {
          "id": 3,
          "toolId": 3,
          "isError": true,
          "tokens": 10
        },
        {
          "id": 4,
          "toolId": 2,
          "isError": true,
          "tokens": 70
        }
      ],
      "children": [
        [
          1,
          2
        ],
        [],
        [
          3,
          4
        ],
        [],
        []
      ]
    },
    "queries": [
      0,
      2
    ],
    "expected": [
      {
        "topErrorTool": 1,
        "topErrorCount": 2,
        "distinctErrorTools": 3,
        "wastedTokens": 380
      },
      {
        "topErrorTool": 1,
        "topErrorCount": 1,
        "distinctErrorTools": 3,
        "wastedTokens": 280
      }
    ]
  },
  {
    "id": "capstone-3",
    "number": 3,
    "slug": "ai-gateway",
    "kind": "alternative",
    "chip": "Gateway",
    "chipClass": "chip--violet",
    "title": "Capstone 3 - Enterprise Multi-Model AI Gateway",
    "subtitle": "OpenRouter-inspired control + request plane",
    "weeks": "Weeks 103–108 · alternative",
    "image": "/images/capstone3_enterprise_ai_gateway.webp",
    "description": "An OpenRouter-inspired final capstone: design and build the control plane, request plane, routing policy, reliability layer, enterprise tenancy, and economics behind a unified multi-model AI gateway.",
    "points": [
      "One API → many models and providers",
      "Policy-compliant, explainable routing",
      "Stream-safe failover, idempotency, admission",
      "Append-only usage and cost ledger",
      "24-point rubric, PII-safe observability"
    ],
    "proseSource": "CAPSTONE3_OPENROUTER.md",
    "artifactType": "enterprise_gateway",
    "promises": [
      {
        "label": "one API",
        "desc": "a normalized endpoint that hides provider-specific wire formats"
      },
      {
        "label": "many models and providers",
        "desc": "a versioned registry of capabilities, regions, prices, and health"
      },
      {
        "label": "policy-compliant routing",
        "desc": "filter by capability, region, data policy, allowlist, budget, and health"
      },
      {
        "label": "reliable streaming and failover",
        "desc": "pre-token failover; post-token error, never silent replay"
      },
      {
        "label": "tenant isolation and fair admission",
        "desc": "per-workspace budgets, concurrency, priority, fencing"
      },
      {
        "label": "exact usage and cost evidence",
        "desc": "append-only idempotent ledger, deterministic settlement"
      },
      {
        "label": "enterprise controls and operational trust",
        "desc": "SSO, guardrails, audit, SLAs, invoicing boundaries"
      }
    ],
    "failureMatrix": [
      {
        "id": "provider-timeout-before-tokens",
        "failure": "Provider timeout before tokens",
        "expectedBehavior": "Retry/fail over within bounded retry budget"
      },
      {
        "id": "provider-disconnect-after-first-token",
        "failure": "Provider disconnect after first token",
        "expectedBehavior": "Do not transparently replay; emit stream error and partial-attempt event"
      },
      {
        "id": "no-compliant-provider",
        "failure": "No provider meets ZDR/region policy",
        "expectedBehavior": "Fail closed; explain rejected candidates"
      },
      {
        "id": "duplicate-idempotency-key",
        "failure": "Duplicate idempotency key",
        "expectedBehavior": "Return/reconcile the original logical request according to contract"
      },
      {
        "id": "workspace-budget-exhausted",
        "failure": "Workspace budget exhausted",
        "expectedBehavior": "Reject before provider dispatch"
      },
      {
        "id": "tenant-concurrency-saturated",
        "failure": "Tenant concurrency saturated",
        "expectedBehavior": "Queue, reject, or shed according to priority policy"
      },
      {
        "id": "leader-lease-expires-mid-admission",
        "failure": "Leader lease expires mid-admission",
        "expectedBehavior": "Fencing prevents stale owner from committing admission"
      },
      {
        "id": "provider-price-changes",
        "failure": "Provider price changes",
        "expectedBehavior": "New version applies to new decisions; old ledger remains reproducible"
      },
      {
        "id": "malformed-provider-usage",
        "failure": "Malformed provider usage",
        "expectedBehavior": "Quarantine settlement and alert; never invent silent cost"
      },
      {
        "id": "pii-appears-in-payload",
        "failure": "PII appears in payload",
        "expectedBehavior": "Redact or reject before durable trace emission"
      }
    ],
    "interviewQuestions": [
      "Why is the gateway valuable if providers already expose APIs?",
      "What must be strongly consistent, and what can be eventually consistent?",
      "How do you prove a fallback did not violate data policy?",
      "When is retrying a stream unsafe?",
      "How do you prevent one tenant from buying all provider capacity?",
      "How do you reconcile provider usage with customer invoices?",
      "Which features should be bought from an identity, billing, or observability vendor?"
    ],
    "rubric": {
      "points": 24,
      "dimensions": [
        "product boundary",
        "API normalization",
        "registry",
        "routing",
        "data policy",
        "reliability",
        "tenancy",
        "accounting",
        "observability",
        "security",
        "benchmark",
        "staff defense"
      ],
      "scoring": "Score each dimension 0–2.",
      "passing": "18/24, no zero in policy, reliability, tenancy, or accounting, and a complete evidence bundle."
    }
  }
];

export const CAPSTONE_1: Capstone = CAPSTONES[0]!;
export const CAPSTONE_2: Capstone = CAPSTONES[1]!;
export const CAPSTONE_3: Capstone = CAPSTONES[2]!;
