// @generated by tools/generate.py; edit schema/*.yaml instead.
/**
 * Parallel deep-dive catalog.
 *
 * The canonical metadata lives in schema/deep_dives.yaml.  This typed view is
 * consumed by the Astro page until the schema generator emits site data.
 */

export interface DeepDiveReference {
  week?: number;
  track?: string;
  capstone?: number;
  role: string;
  primitive?: string;
}

export interface DeepDiveArtifact {
  id: string;
  title: string;
  path: string;
  sizeKb: number;
  tier: 'core' | 'optional' | 'archive';
  level: 1 | 2 | 3;
  sectionCount: number;
  pairId: string;
  pairRole: 'theory' | 'production';
  prerequisiteOf?: string;
  selectionRationale: string;
  crossReferences: DeepDiveReference[];
}

export interface DeepDiveTrack {
  id: string;
  title: string;
  shortName: string;
  parallelTrack: true;
  pairEnforcement: 'strict';
  tier: 'core' | 'optional' | 'archive';
  level: 1 | 2 | 3;
  seam: string;
  selectionRationale: string;
  loadBearingFor: DeepDiveReference[];
  crossReferences: DeepDiveReference[];
  primaryArtifacts: DeepDiveArtifact[];
}

const CROSS_REFERENCES: DeepDiveReference[] = [
  { week: 31, role: 'cosine similarity and normalized vectors' },
  { week: 36, role: 'length-weighted pooling and IDF' },
  { week: 39, role: 'Recall@K, MRR, and NDCG' },
  { week: 77, role: 'graph traversal, decay, and fusion' },
  { week: 78, role: 'dynamic thresholding and retrieval evaluation' },
  { week: 81, role: 'tool graph and Adamic-Adar' },
  { week: 86, role: 'telemetry-based reranking' },
  { week: 94, role: 'multi-signal routing' },
  { week: 97, role: 'type affinity and tenant policy' },
  { capstone: 3, role: 'multi-signal OpenRouter gateway' },
];

const SEARCH: DeepDiveArtifact = {
  id: 'search_md',
  title: 'SEARCH.md - Multi-signal recommendation math',
  path: 'SEARCH.md',
  sizeKb: 25,
  tier: 'optional',
  level: 2,
  sectionCount: 17,
  pairId: 'tool_recommendation_systems',
  pairRole: 'theory',
  selectionRationale:
    'Level 2 treatment of recommendation math: graph representation, cosine similarity with normalization, length-weighted pooling, hop decay, Adamic-Adar with hub defence, IDF weighting, intent and type affinity, dynamic noise-floor filtering, multi-signal combination, implementable pseudocode, production failure modes, telemetry-based weight learning, and retrieval/ranking/diversity/operational evaluation.',
  crossReferences: CROSS_REFERENCES,
};

const SNOWFLAKE: DeepDiveArtifact = {
  id: 'snowflake_md',
  title: 'SNOWFLAKE.md - Production Snowflake implementation',
  path: 'SNOWFLAKE.md',
  sizeKb: 32,
  tier: 'optional',
  level: 3,
  sectionCount: 24,
  pairId: 'tool_recommendation_systems',
  pairRole: 'production',
  prerequisiteOf: 'search_md',
  selectionRationale:
    'Level 3 implementation in production Snowflake SQL: entity, edge, type-affinity, token, and term-stat schemas; AI_EMBED and VECTOR storage; recursive-CTE graph walks with cycle prevention; weighted Adamic-Adar; min-max normalization; PERCENTILE_CONT thresholds; Cortex Search serving; and Streams + Tasks for incremental refresh. It exposes AI_EMBED permissions, recursive-CTE safety, serving latency, and credit economics.',
  crossReferences: CROSS_REFERENCES,
};

export const TOOL_RECOMMENDATION_SYSTEMS: DeepDiveTrack = {
  crossReferences: [{ role: 'shares the agent-tool graph model', track: 'agents' }, { role: 'shares Recall@K / MRR evaluation', track: 'darbar' }, { role: 'shares graph-traversal algorithmic depth', track: 'forge' }, { capstone: 3, role: 'shares the multi-signal routing pattern' }],
  id: 'tool_recommendation_systems',
  level: 2,
  loadBearingFor: [{ primitive: 'cosine similarity + length-weighted pooling', role: 'retrieval math', week: 31 }, { primitive: 'IDF-weighted token scoring', role: 'chunk and lexical scoring', week: 36 }, { primitive: 'Recall@K, MRR, NDCG evaluation', role: 'ranking metrics', week: 39 }, { primitive: 'graph traversal + hop decay', role: 'retrieval patterns', week: 77 }, { primitive: 'dynamic noise-floor filtering', role: 'retrieval evaluation', week: 78 }, { primitive: 'Adamic-Adar for tool graph', role: 'agent foundations', week: 81 }, { primitive: 'operational telemetry into ranking', role: 'monitoring', week: 86 }, { primitive: 'multi-signal router', role: 'traffic routing', week: 94 }, { primitive: 'type affinity for tenant policies', role: 'quotas and priority', week: 97 }, { capstone: 3, primitive: 'OpenRouter gateway as multi-signal recommender', role: 'capstone integration' }],
  pairEnforcement: 'strict',
  parallelTrack: true,
  primaryArtifacts: ['SEARCH', 'SNOWFLAKE'],
  seam: 'multi-signal recommendation over graph + embedding + metadata',
  selectionRationale: 'The pair is the seam philosophy applied to recommendation systems. SEARCH.md introduces the elegant math (graph traversal, hop decay, Adamic-Adar, IDF, type affinity, dynamic thresholds, and multi-signal combination) at Level 2. SNOWFLAKE.md implements that same theory in production Snowflake SQL and exposes where the math dies on contact with AI_EMBED permissions, recursive-CTE cycle prevention, Cortex Search latency, and Snowflake credit burn. The spine covers every primitive implicitly (W31, W36, W39, W77, W78, W81, W86, W94, W97) but never formalizes their combination, so this opt-in track makes it load-bearing without adding another spine phase.',
  shortName: 'recommender',
  tier: 'optional',
  title: 'Tool Recommendation Systems',
};

export const DEEP_DIVES: DeepDiveTrack[] = [TOOL_RECOMMENDATION_SYSTEMS];
export const DEEP_DIVE_TRACKS = DEEP_DIVES;
export const RECOMMENDER_TRACK = TOOL_RECOMMENDATION_SYSTEMS;
export const RECOMMENDER_ARTIFACTS = TOOL_RECOMMENDATION_SYSTEMS.primaryArtifacts;
