// @generated by tools/generate.py; edit schema/*.yaml instead.
/**
 * The 16-mandala capability progression.
 * A mandala is 48 days; the 108-week course is 15 full mandalas + a final 36-day
 * graduation mandala = 756 days. Transcribed from MANDALA.md.
 */

export interface Mandala {
  id: string;
  title: string;
  days: string;
  weeks: string;
  identity: string;
  topics: string[];
  evidence: string[];
  transformation: string;
}

export const MANDALAS: Mandala[] = [
  {
    id: '1',
    title: 'Build the learner’s operating system',
    days: 'Days 1–48',
    weeks: 'Weeks 1–7',
    identity: 'Disciplined learner',
    topics: [
      'Python engineering, typing, testing and async fundamentals',
      'NumPy, vectorization and broadcasting',
      'Git, notebooks, Makefiles and reproducible experiments',
      'Docker, HTTP, APIs and Linux basics',
      'Personal mathematics and systems diagnostics',
      'Weekly journals, evidence tracking and retrospectives',
      'Vector spaces, span, basis and dimension',
    ],
    evidence: [
      'course dashboard and repository',
      'tested CLI project',
      'numerical utility library',
      'reproducible notebook',
      'diagnostic gap map',
      'containerized service',
      'first mathematics problem set',
    ],
    transformation:
      'They stop being someone “planning to study AI” and become someone with a functioning learning and engineering system.',
  },
  {
    id: '2',
    title: 'Learn the geometry beneath intelligence',
    days: 'Days 49–96',
    weeks: 'Weeks 7–14',
    identity: 'Linear-algebra thinker',
    topics: [
      'Linear independence, rank and nullity',
      'Inner products and dual norms',
      'Orthogonality and projections, Gram–Schmidt',
      'Coordinate transformations',
      'Eigenvalues and diagonalization',
      'PSD matrices and quadratic forms, Rayleigh quotients',
      'SVD, pseudoinverse and low-rank approximation',
    ],
    evidence: [
      'projection and coordinate-transformation labs',
      'PCA-style experiment',
      'quadratic-form visualization',
      'low-rank compression demo',
    ],
    transformation:
      'Embeddings, attention and matrix models stop looking like mystical equations. The learner can reason geometrically.',
  },
  {
    id: '3',
    title: 'Numerical computation and differentiation',
    days: 'Days 97–144',
    weeks: 'Weeks 14–21',
    identity: 'Numerical programmer',
    topics: [
      'Matrix norms and conditioning, perturbation analysis',
      'LU, QR and Cholesky',
      'Iterative solvers, power iteration and Krylov methods',
      'Randomized SVD, tensor notation',
      'Partial and directional derivatives',
      'Gradients, Jacobians and Hessians, Taylor approximations',
      'Chain rule on computational graphs',
    ],
    evidence: [
      'numerical decomposition library',
      'solver benchmarks',
      'perturbation experiment',
      'randomized approximation lab',
      'gradient and curvature visualizers',
      'manual backpropagation worksheet',
    ],
    transformation:
      'They begin understanding not only whether an algorithm is mathematically correct, but whether it is numerically sane.',
  },
  {
    id: '4',
    title: 'Probability, autodiff and statistical inference',
    days: 'Days 145–192',
    weeks: 'Weeks 21–28',
    identity: 'Statistical reasoner',
    topics: [
      'Computational graphs, forward/reverse-mode autodiff, JVPs and VJPs',
      'Probability spaces, conditional probability and Bayes',
      'Random variables and distributions',
      'Covariance and correlation',
      'LLN, CLT and delta method',
      'MLE and MAP, estimator bias and variance',
      'Hypothesis testing, Type I and Type II errors',
    ],
    evidence: [
      'tiny autodiff engine',
      'probability simulations',
      'covariance analysis',
      'Monte Carlo convergence demo',
      'estimator comparison',
      'statistical-test implementation',
    ],
    transformation:
      'They can explain why training and evaluation procedures work — not merely import them.',
  },
  {
    id: '5',
    title: 'Experimentation meets retrieval',
    days: 'Days 193–240',
    weeks: 'Weeks 28–35',
    identity: 'Retrieval and experimentation builder',
    topics: [
      'p-values, confidence intervals, bootstrap and permutation tests',
      'power, MDE and sample-size calculations, multiple-testing correction',
      'cosine similarity, exact and memory-bounded KNN',
      'streaming Top-K and dynamically changing scores',
      'two-stage retrieval and reranking',
      'sliding-window and token-bucket rate limiting',
      'LRU and TTL caching',
    ],
    evidence: [
      'bootstrap CI package',
      'experiment-size calculator',
      'vector-search mini-lab',
      'Top-K service',
      'reranking prototype',
      'rate-limiter module',
      'cache simulator',
    ],
    transformation:
      'They can now build the primitives behind search, experimentation and traffic control.',
  },
  {
    id: '6',
    title: 'Production reliability and measurable AI',
    days: 'Days 241–288',
    weeks: 'Weeks 35–42',
    identity: 'Reliability-minded engineer',
    topics: [
      'text and sentence-aware chunking',
      'PII span merging, regex and NER-based redaction',
      'Expected Calibration Error, Brier score and reliability diagrams',
      'NDCG, MRR and Recall@K',
      'thread-safe inference batching',
      'retries, exponential backoff and jitter, circuit breakers',
      'Count-Min Sketch and Bloom filters',
    ],
    evidence: [
      'chunking library',
      'safe redaction utility',
      'calibration dashboard',
      'retrieval evaluator',
      'concurrent batcher',
      'fault-tolerance toolkit',
      'probabilistic data structures',
    ],
    transformation:
      'They stop thinking only about model output and start thinking about trust, failure, observability and operational behavior.',
  },
  {
    id: '7',
    title: 'Distributed primitives and design reasoning',
    days: 'Days 289–336',
    weeks: 'Weeks 42–48',
    identity: 'Distributed-systems implementer',
    topics: [
      'HyperLogLog, consistent hashing, rendezvous hashing',
      'weighted load balancing, distributed unique IDs',
      'leaky-bucket and sliding-window counters',
      'requirements and constraint gathering, APIs and data modelling',
      'observability, rate limiting at distributed scale',
    ],
    evidence: [
      'cardinality estimator',
      'routing lab',
      'load-balancer module',
      'platform-primitives library',
      'system-design document template',
      'first complete design exercises',
    ],
    transformation:
      'They can move from implementing one process to reasoning about many machines.',
  },
  {
    id: '8',
    title: 'Classic distributed systems',
    days: 'Days 337–384',
    weeks: 'Weeks 49–55',
    identity: 'System designer',
    topics: [
      'scaling reads and writes, caching and replication, contention',
      'large blob storage and CDNs',
      'orchestration versus choreography, workflow-state ownership',
      'backward-compatible schema evolution',
      'URL shorteners, Dropbox, Ticketmaster, News Feed, WhatsApp, LeetCode-style judges',
    ],
    evidence: [
      'scaling-pattern notes',
      'blob-storage design',
      'workflow-state architecture',
      'schema-migration plan',
      'multiple end-to-end design documents',
    ],
    transformation:
      'They stop naming technologies and start defending architecture.',
  },
  {
    id: '9',
    title: 'From system design to ML product science',
    days: 'Days 385–432',
    weeks: 'Weeks 55–62',
    identity: 'ML systems practitioner',
    topics: [
      'Uber and web crawlers, ad-click aggregation, payments',
      'business-objective formulation, model-versus-non-model decisions',
      'labeling and weak supervision, data augmentation',
      'leakage and contamination, experiment tracking and versioning',
      'baselines, slice-based offline evaluation, confidence intervals',
      'shadow and canary deployment, bandits',
    ],
    evidence: [
      'ML project charter',
      'data-quality checklist',
      'leakage audit',
      'evaluation harness',
      'rollout plan',
    ],
    transformation:
      'They learn that a production ML system begins with a decision and a dataset — not with model training.',
  },
  {
    id: '10',
    title: 'Build a mature experimentation platform',
    days: 'Days 433–480',
    weeks: 'Weeks 62–69',
    identity: 'Experimentation engineer',
    topics: [
      'A/B-test significance calculation, absolute and relative lift',
      'pooled standard errors, confidence intervals',
      'paired bootstrap model comparison',
      'Sample-Ratio Mismatch detection, chi-square diagnostics',
      'feature-flag engines, deterministic sticky assignment',
      'monitoring and drift detection, production incident analysis',
    ],
    evidence: [
      'analyze_ab_test',
      'bootstrap comparison package',
      'SRM detector',
      'feature-flag service',
      'experiment-assignment service',
      'monitoring specification',
      'incident postmortem',
    ],
    transformation:
      'They can distinguish “the metric increased” from “we have trustworthy evidence that the product improved.”',
  },
  {
    id: '11',
    title: 'Train, align and retrieve with LLMs',
    days: 'Days 481–528',
    weeks: 'Weeks 69–76',
    identity: 'LLM training and retrieval engineer',
    topics: [
      'transformer and tokenizer anatomy, training-data cleaning and deduplication',
      'SFT, LoRA, QLoRA and DoRA',
      'RLHF, DPO, ORPO and GRPO',
      'DDP and FSDP, tensor and pipeline parallelism, ZeRO',
      'HNSW, IVF-PQ and product quantization',
      'hybrid retrieval, query rewriting, parent–child and multi-vector retrieval',
    ],
    evidence: [
      'model-anatomy notes',
      'dataset card',
      'fine-tuning plan',
      'preference-evaluation plan',
      'distributed-training architecture',
      'vector-index benchmark',
      'retrieval lab',
    ],
    transformation:
      'They understand the whole upstream and retrieval lifecycle rather than treating the LLM as a remote magic endpoint.',
  },
  {
    id: '12',
    title: 'RAG, agents and inference foundations',
    days: 'Days 529–576',
    weeks: 'Weeks 76–83',
    identity: 'RAG and agent engineer',
    topics: [
      'BM25 + dense + reranker fusion, Reciprocal Rank Fusion',
      'evaluation by query slice',
      'prompt templates and version registries',
      'conversation and long-term memory, context-window optimization',
      'ReAct, plan-and-execute, tool calling, agent guardrails',
      'GPU compute-, memory- and overhead-bound regimes, FlashAttention',
      'roofline models and arithmetic intensity',
    ],
    evidence: [
      'retrieval-fusion service',
      'regression report',
      'prompt-management tool',
      'memory service',
      'agent prototype',
      'GPU performance primer',
      'arithmetic-intensity worksheet',
    ],
    transformation:
      'They can build an agent and explain where its latency, errors, context and cost come from.',
  },
  {
    id: '13',
    title: 'Become an inference systems engineer',
    days: 'Days 577–624',
    weeks: 'Weeks 83–90',
    identity: 'Inference performance engineer',
    topics: [
      'PagedAttention, KV-cache block tables, vLLM deployment',
      'scheduler and block-manager internals, running/waiting metrics',
      'latency histograms, Prometheus and Grafana',
      'request-rate sweeps and saturation analysis',
      'SGLang, RadixAttention and prefix reuse',
      'Orca-style continuous batching, chunked prefill',
    ],
    evidence: [
      'live vLLM deployment',
      'internal architecture notes',
      'metrics schema',
      'serving dashboard',
      'benchmark methodology',
      'vLLM/SGLang comparison',
      'scheduling report',
    ],
    transformation:
      'They can diagnose inference rather than simply complain that it is slow.',
  },
  {
    id: '14',
    title: 'Advanced serving and reliable routing',
    days: 'Days 625–672',
    weeks: 'Weeks 90–96',
    identity: 'Serving and routing engineer',
    topics: [
      'continuous batching trade-offs, FP8, AWQ and GPTQ',
      'KV-cache compression, speculative decoding, Medusa and EAGLE',
      'StreamingLLM and KV eviction',
      'DistServe, Splitwise and Mooncake, prefill/decode disaggregation',
      'model routing, canary assignment and kill switches',
      'PII-safe traces and logs, async fan-out, partial failures, token-stream multiplexing',
    ],
    evidence: [
      'quality-versus-throughput benchmark',
      'latency and memory lab',
      'disaggregated serving architecture',
      'model-router service',
      'safe tracing layer',
      'resilient aggregator',
    ],
    transformation:
      'They can optimize not just a model, but a multi-provider inference service.',
  },
  {
    id: '15',
    title: 'Build the enterprise AI platform',
    days: 'Days 673–720',
    weeks: 'Weeks 97–103',
    identity: 'Multi-tenant AI platform engineer',
    topics: [
      'distributed token budgets, request prioritization',
      'DAG workflow execution, idempotency',
      'per-tenant concurrency limits, leader election',
      'distributed work queues, dynamic configuration',
      'model health monitoring, registries and promotion',
      'semantic and embedding caches, prompt-injection detection',
      'exact cost attribution, capstone architecture planning',
    ],
    evidence: [
      'quota and priority service',
      'workflow engine',
      'tenant limiter',
      'HA lab',
      'queue/configuration platform',
      'model-operations pipeline',
      'cost/safety platform',
      'complete capstone design document',
    ],
    transformation:
      'This is where “tensor” finally becomes “tenant.”',
  },
  {
    id: 'final',
    title: 'Graduation — portfolio, capstone and interview readiness',
    days: 'Days 721–756',
    weeks: 'Weeks 103–108',
    identity: 'Portfolio-backed Staff AI Systems candidate',
    topics: [
      'complete the capstone core API',
      'build the retrieval or agent flow',
      'install evaluation, tracing and guardrails',
      'run load and failure tests, tune latency and cost',
      'produce architecture and benchmark reports',
      'complete coding, system-design and behavioral mocks',
      'publish the portfolio, perform a full retrospective',
      'create a 30-day career plan',
    ],
    evidence: [
      'repository, traces, benchmarks, design documents and failure tests',
      'published portfolio release',
      'mock-interview scorecard',
      '30-day job-search plan',
    ],
    transformation:
      'They no longer need to tell someone they “know AI systems.” They can provide the repository, traces, benchmarks, design documents and failure tests.',
  },
];

/** The identity gained at the end of each mandala. */
export const IDENTITY_LADDER = MANDALAS.map((m) => ({
  id: m.id,
  title: m.title,
  identity: m.identity,
  weeks: m.weeks,
}));
